### ISSUE TITLE
Pass props to custom option

### ISSUE THREAD

**Issue by LukasLoeffler** [newcat/baklavajs#105]
First of all I have to say, that baklavajs is quite intuitive and a pleasure to use.

However there is on thing I don't quite understand or that doesn't work properly.
I use baklavajs in a vue application created by vue-cli.
I wanted to create a Node with a Button that implements my own logic on click. Therefore I created a _ButtonNode.ts_ with the following code:

```
import { NodeBuilder } from "@baklavajs/core";

export default new NodeBuilder("button")
    .setName("Button")
    .addOption("BtnEvent", "EventButton", undefined, undefined, { 
        title: "Exec", 
        value: "exec1",
    })
    .addOutputInterface("onSuccess")
    .build();
```

I also created my own option component with the following code:
```
<template>
    <button @click="onClick" class="dark-button --block">{{title}}</button>
</template>

<script>
export default {
    props: ["title", "value"],
    methods: {
        onClick() {
            let clickEvent = {
                title: this.title,
                val: this.value,
            }
            this.$emit('clickEvent', clickEvent);
        }
    }
}
</script>
```

I also registered the option in accordance to the documentation.

The Node with the Button appear in the editor but the title which I passed as property does not show up in the ui. But the value property can be used in the component.

Did I pass the props correctly and if not how would you properly pass them?

**Comment by newcat** [comment]
I think it is easier to handle an event when not using the `NodeBuilder`, but a `class extends Node` instead.

For example:
```js
import { Node } from "@baklavajs/core";

export default class ButtonNode extends Node {
  type = "ButtonNode";
  name = this.type;

  constructor() {
    super();
    this.addOption("BtnEvent", "EventButton", undefined, undefined, { value: "exec1", value: "exec1" });
    this.addOutputInterface("onSuccess");
  }

  onClick(ev) {
    console.log(ev);
  }
}
```

Then you can implement your `EventButton` option like this:
```vue
<template>
    <button @click="onClick" class="dark-button --block">{{option.title}}</button>
</template>

<script>
export default {
    props: ["option", "node", "value"],
    methods: {
        onClick() {
            this.node.onClick({
                title: this.option.title,
                val: this.value,
            });
        }
    }
}
</script>
```

You can find all props passed to a node option [here](https://newcat.github.io/baklavajs/#/node-options). Unfortunately, using Vue events does not work, so you need to call the method on the node directly. The only two Vue events supported for node options are `input` and `openSidebar`.

**Comment by LukasLoeffler** [comment]
Thank you for your fast reply.
Rewriting the code as node class helped and works as expected.
Your explanation/code example helped me to understand the concept and the idea behind the options.

Thanks for your help!
