### ISSUE TITLE
Using Interface Types

### ISSUE THREAD

**Issue by LukasLoeffler** [newcat/baklavajs#108]
I want to add color to the interface of a node (I saw that use-case on the screenshot in the Readme where the color interfaces are colored yellow)

I had a look into the documentation where the interface types are mentioned which contain a type and a color. I guess thats the right choice for styling the nodes and prevent the connection of nodes with different types.

I registered some types as described in the documentation. But from the registration on there is no explanation on how to use the interface type. I had a look through the documentation and didnt find an example on how to actuually use them after registration.

Have I overlooked something and if not, how do I use the interface types?

Thanks in advance!

**Comment by newcat** [comment]
Updated the [docs](https://newcat.github.io/baklavajs/#/plugins/interface-types) - the usage was indeed missing completely. Thanks for the issue!
