### ISSUE TITLE
Distiguish between input and output interfaces

### ISSUE THREAD

**Issue by LukasLoeffler** [newcat/baklavajs#109]
For context: I use BaklavaJS in my masters degree to build the frontend for a data pipelining tool, where the nodes are data processing nodes and the connections between these nodes define the dataflow. The output of the editor.save() method is passed to the backend which builds a graph out of the frontend representation. (Great framework for such tools btw.)

The current procedure to distinguish whether an interface is input or output is to check, if the interfaceId appears in the connections array in the 'from' or in the 'to' field. 
This works great unless the interface is not connected. In this case there is also no connection to check the 'to' and the 'from' field.

To my question: Is it possible to overwrite the save function if the interface with isInput as additional field?

For example the save method of the nodeInterface?
```
    public save(): IInterfaceState {
        const state = {
            id: this.id,
            value: this.value,
            isInput: this.isInput
        };
        return this.hooks.save.execute(state);
    }
```

Another usecase not only for some backend, but also for BaklavaJS is the dynamic number of interfaces on a single node. 
I wrote an node for my usecase with a dynamic number of inputs. In this case the distinction between inputs and outputs is crucial, because Baklava itself cant map the interfaces to input and output by the name of the interface (not initialized yet). For this case I have overwritten the load function of the Node and did the distinction by the name (Not perfect solution due to the unconciseness of the includes function but works for the moment):
```
    load(data) {
        this.id = data.id;
        this.name = data.name;
        this.state = data.state;

        data.interfaces.forEach(([k, v]) => {
            if(k.includes("IN") || k.includes("in")) {
                this.addInputInterface(k);
            }
            
            if (this.interfaces.has(k)) {
                this.interfaces.get(k).load(v);
            }
        });
        data.options.forEach(([k, v]) => {
            if (this.options.has(k)) {
                this.options.get(k).value = v;
            }
        });
        this.hooks.load.execute(data);
    }
```
![image](https://user-images.githubusercontent.com/24526399/100163308-aeb52f00-2eb5-11eb-9b81-be8707ae3583.png)

**Comment by newcat** [comment]
Not tested, but you could do something like this in your node class:
```js
public save() {
    const state = super.save();
    state.interfaces.forEach(([name, intfState]) => {
        intfState.isInput = this.getInterface(name).isInput;
    });
    return state;
}

public load(state) {
    state.interfaces.forEach(([name, intfState]) => {
        const intf = intfState.isInput ? this.addInputInterface(name) : this.addOutputInterface(name);
        intf.id = intfState.id;
    });
    super.load(state);
}
```

**Comment by LukasLoeffler** [comment]
I have tested it and it works as expected. Thanks for the helpful reply 👍.

Dou you have future plans to add the possibility for a node with a variable amount of interfaces by default? This feature might interfere with the engine plugin.

**Comment by newcat** [comment]
I have added it to the v2 backlog. Not sure how I am going to implement it, but I'll think about it.
