### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by AlteredCarbonate** [newcat/baklavajs#114]
Hello there everyone!

I love this project so far, and tried to a lot around.
Sadly I fail to understand, how certain things work.

Biggest Problem is calculation?
A simple flow from

Node: Text -> Node: console.log

I fail to understand... How's everything working together?
What is emitting the calculation?

Best regards, Carbon!

**Comment by newcat** [comment]
Sorry, I don't really understand what problem you are facing exactly. Everything related to calculation is handled by the `Engine` plugin. The documentation can be found here: https://newcat.github.io/baklavajs/#/plugins/engine
