### ISSUE TITLE
Cannot create node from external file

### ISSUE THREAD

**Issue by jmguil** [newcat/baklavajs#115]
Hello,
Sorry if my question is stupid, but i'am struggled for two days while attempting to create a node defined into another file.
I'am using the version 1.8.2 of baklava.

Here is my setup:
**The TestEditor.vue file:**
```javascript
<template>
  <div style="width:100vw;height:100vh">
    <baklava-editor :plugin="viewPlugin"></baklava-editor>
  </div>
</template>

<script>
import { Editor, NodeBuilder } from '@baklavajs/core'
import { ViewPlugin } from '@baklavajs/plugin-renderer-vue'
import { OptionPlugin } from '@baklavajs/plugin-options-vue'
import InputNode from './InputNode'

export default {
  name: 'TestEditor',
    data () {
        return {
          editor: new Editor(),
          viewPlugin: new ViewPlugin(),
          optionPlugin: new OptionPlugin()
    }
  },
  created () {
    this.editor.use(this.optionPlugin)
    this.editor.use(this.viewPlugin)
    this.viewPlugin.enableMinimap = true
    this.editor.registerNodeType('InputNode', InputNode)
    this.editor.registerNodeType('OntheFlyNode=', new NodeBuilder('OntheFlyNode', { twoColumn: true }).build())
  }
}
</script>
```

**And here is the content of InputNode.vue:**
```javascript
import { Node } from "@baklavajs/core";

export default class InputNode extends Node {
  public type = "InputNode";
  public name = this.type;

  public constructor() {
    super();
    this.addOutputInterface("Output", { twoColumn: true });
  }

  public load(state) {
    super.load(state);
  }
}
```

The editor is well loaded, the minimap is ok, if i try to add the OntheFlyNode no problem, but if i try to add the InputNode i get the following message in the console:

__TypeError: nt is not a constructor
    at VueComponent.EditorView.onContextMenuClick (index.js?420b:1687)
    at invokeWithErrorHandling (vue.runtime.esm.js?5593:1854)
    at VueComponent.invoker (vue.runtime.esm.js?5593:2179)
    at invokeWithErrorHandling (vue.runtime.esm.js?5593:1854)
    at VueComponent.Vue.$emit (vue.runtime.esm.js?5593:3888)
    at VueComponent.ContextMenu.onChildClick (index.js?420b:2434)
    at invokeWithErrorHandling (vue.runtime.esm.js?5593:1854)
    at VueComponent.invoker (vue.runtime.esm.js?5593:2179)
    at invokeWithErrorHandling (vue.runtime.esm.js?5593:1854)
    at VueComponent.Vue.$emit (vue.runtime.esm.js?5593:3888)__

It seems that the content of the file is not loaded as an object.
Does anyone as an idea of what i'am doing wrong? 

Thanks a lot.

**Comment by newcat** [comment]
Not sure if it was just a C&P mistake when creating the issue, but make sure your InputNode file has a .js extension, not a .vue extension

**Comment by jmguil** [comment]
> Not sure if it was just a C&P mistake when creating the issue, but make sure your InputNode file has a .js extension, not a .vue extension

Hi, it is not a C&P mistake, i'am using Vue, through the Quasar Framework to be exact.

**Comment by newcat** [comment]
Ok, but as the node is not a Vue component but just plain Javascript, the file needs to be named `InputNode.js`

**Comment by jmguil** [comment]
> Ok, but as the node is not a Vue component but just plain Javascript, the file needs to be named `InputNode.js`

:-) Works better now. I was confused as the options are components, i thought that all were components. 

Thanks a lot for your help, and congrats for your work. This is awesome !
