### ISSUE TITLE
Custom Option Vue Component example

### ISSUE THREAD

**Issue by pepo205** [newcat/baklavajs#116]
According with this spec, https://newcat.github.io/baklavajs/#/node-options
Do you have any example, about how would it be MyOption.vue?
Thx in advance

**Comment by newcat** [comment]
You can have a look at the options of the option plugin, for example the [CheckboxOption](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-options-vue/src/CheckboxOption.vue) or the [InputOption](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-options-vue/src/InputOption.vue)
