### ISSUE TITLE
Option-change Event

### ISSUE THREAD

**Issue by LukasLoeffler** [newcat/baklavajs#117]
I want to implement a save button which only becomes active if something on the graph is changed. The scaling and the panning of the interface works well. Custom options also work well to detect the changes applied to the node.
The only events I was not able to catch are the option changes from the options provided by the library.

I searched the doumentation but did not find a solution for my problem. The only thing that I am aware of is the possibility to rewrite the native options as custom options. Is there any simpler solution?

**Comment by newcat** [comment]
Did you use the `update` event on the nodes? It should fire whenever any interface value or option value is changed.

**Comment by LukasLoeffler** [comment]
I dont know where to register the listener.
I think that the documentation does not explain the registration in **Usage > Event System**.

**Comment by newcat** [comment]
```js
const n = new Node();
n.events.update.addListener(this, () => { doSomething(); });
```

`this` is just a token for unsubscribing, it can be any non-primitive type or a symbol. But usually you use this in a class or component, so you can just use `this` and later call
```js
n.events.update.removeListener(this);
```

The engine plugin actually uses the `update` event to detect when to recalculate, so you can look at the code as an example: https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-engine/src/engine.ts#L65-L74

**Comment by LukasLoeffler** [comment]
Adapted your snippet and added it to the construcotor of the file.
```
this.events.update.addListener(this, () => {
    store.commit("setDataChanged", true);
});
```
Works as expected. Thanks for your help!
