### ISSUE TITLE
Question: possible to connect multiple outputs to single input interface?

### ISSUE THREAD

**Issue by bwatanabe** [newcat/baklavajs#121]
Not an issue but a question: I'm trying to create an Adobe XD style prototype authoring interface, where each node would represent a slide / page. I want each node / slide to have a single input, with the ability of many other nodes to connect to that single input. Is it possible for me to allow multiple connections to a single input? What I'm hoping is that I can, and that those connections would all show in the connections object when I save to JSON.
I looked at checkConnection() in the editor class but couldn't find a way to do it.
Thanks for any insight.

**Comment by newcat** [comment]
Multiple connections to an input interface are only prevented by the engine plugin. If you don't use the engine plugin, you should be good to go.

**Comment by bwatanabe** [comment]
Thanks for the quick response. I was using the engine plugin, just removed and it's working for me. Thanks again, really great package!
