### ISSUE TITLE
Creating an OptionalFloat option?

### ISSUE THREAD

**Issue by andyqhan** [newcat/baklavajs#122]
For our application of Baklava, we need an option that optionally takes a float. Is this possible in the architecture? I notice that there's only one `value`.

**Comment by newcat** [comment]
Sorry, I am not sure whether I understood your question correctly. Could you give an example?

**Comment by andyqhan** [comment]
Yeah, sorry, that was a bit unclear. 

For example: let's say I'm making an app where a user can model a recipe in Baklava. In the `Ingredient` node, they can specify the `amount` of the `Ingredient` they're adding (this is a regular `IntegerOption`). However, they can also optionally specify how many calories there are per gram of the `Ingredient`. If they do, then the app multiplies the `amount` by this number (a float); if they don't, then the app doesn't calculate calories for that ingredient.

Essentially, I'd like a numeric Option where the user doesn't have to provide a value. In our application, negative and positive and zero values are all valid, so we can't tell them to put in -1 or 0 if they want `null`. 

The current workaround we have is to have a `CheckboxOption` _and_ a `Float` `Option`, and take the `FloatOption` into account only when the `CheckboxOption` is `true`.

**Comment by newcat** [comment]
Your current solution is probably the best you can achieve with only the default options. You can, however, build your own option (which is essentially just a Vue component) and use an object as a value, like this:
```js
{
  enabled: true,
  optionalValue: 0
}
```

Or just make your own custom float option that supports `null` values.

**Comment by andyqhan** [comment]
Ok, sounds good. Thanks for your help!
