### ISSUE TITLE
online demo node editor

### ISSUE THREAD

**Issue by antirek** [newcat/baklavajs#123]
Awesome project! 

Create online demo node editor - for immediate experience ))

**Comment by LukasLoeffler** [comment]
Do you mean something like a CodeSandbox?

**Comment by antirek** [comment]
yes, maybe, for example

**Comment by LukasLoeffler** [comment]
In this [Sandbox](https://codesandbox.io/s/baklava-vuetify-forked-qu4bz) which I forked from Newcat and cleaned a little bit, you can see the example of the MathNode also mentioned in the [Documentation](https://newcat.github.io/baklavajs/#/custom-nodes).

**Comment by antirek** [comment]
I see empty baklavajs field without any nodes. Is mathNode invisible?

**Comment by LukasLoeffler** [comment]
In this case yes. The nodes are not beeing persisted in this example. You can add it by right-clicking into the editor > Add Node > Math Node

**Comment by antirek** [comment]
Thanks, very simple and clear example. 
In this case right-clicking isn't obvious for me ))

**Comment by antirek** [comment]
link to this example must be in readme.md exactly

**Comment by newcat** [comment]
Thanks! Based on your example @LukasLoeffler, I created an example sandbox which also has a tip overlay, since the right-click functionality is definitely not obvious :)

https://codesandbox.io/s/baklavajs-example-jyc6f?file=/src/App.vue

It is also linked in the readme now.
