### ISSUE TITLE
add Input/Output Interfaces programatically

### ISSUE THREAD

**Issue by EduardoBilk** [newcat/baklavajs#127]
I've just discover that [addInputInterface](https://newcat.github.io/baklavajs/api/index.html#/@baklavajs%2Fcore/classes/Node#addInputInterface) and [addOutputInterface](https://newcat.github.io/baklavajs/api/index.html#/@baklavajs%2Fcore/classes/Node#addOutputInterface) are protected!

My goal is to add/remove interfaces programmatically, is there any way to proper do it?

**Comment by LukasLoeffler** [comment]
Why do you think these methods are protected?
Maybe have a look at this [issue](https://github.com/newcat/baklavajs/issues/126). This may help.

**Comment by EduardoBilk** [comment]
I Just checked here: https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-core/src/node.ts

Anyways https://github.com/newcat/baklavajs/issues/126 really helps indeed.

Thank you very much!
