### ISSUE TITLE
addOption not visible

### ISSUE THREAD

**Issue by j2l** [newcat/baklavajs#128]
Hello! Great project!
I followed the docs and love the idea to only work on one html file so I tried on codesandbox and jsfiddle (less errors in console).
https://jsfiddle.net/p89gm7ch/
But MathNode doesn't displays addOptions while I copy pasted from the docs (https://newcat.github.io/baklavajs/#/custom-nodes):
```
const MathNode = new BaklavaJS.Core.NodeBuilder("MathNode")
        .setName("Math")
        .addInputInterface("Number 1", "NumberOption", 1)
        .addInputInterface("Number 2", "NumberOption", 10)
        .addOption("Operation", "SelectOption", "Add", undefined, {
          items: ["Add", "Subtract"]
        })
        .addOutputInterface("Output")
        .onCalculate((n) => {
          const n1 = n.getInterface("Number 1").value;
          const n2 = n.getInterface("Number 2").value;
          const operation = n.getOptionValue("Operation");
          let result;
          if (operation === "Add") {
            result = n1 + n2;
          } else if (operation === "Subtract") {
            result = n1 - n2;
          }
          n.getInterface("Output").value = result;
        })
        .build();
```
Any idea?

**Comment by newcat** [comment]
Please add this line:
`editor.use(new BaklavaJS.PluginOptionsVue.OptionPlugin());`

The option plugin registers all the [prebuilt options](https://newcat.github.io/baklavajs/#/plugins/options) so they can be used by the nodes.

**Comment by j2l** [comment]
Thank you
