### ISSUE TITLE
Add Node Categories

### ISSUE THREAD

**Issue by TinusNL** [newcat/baklavajs#137]
This is not an issue more of an idea. It would be cool if you can add categories to the "Add Node" context menu. Currently, once you add a lot of nodes it becomes difficult to find the right node. Because of this, a search option might also be handy but not necessary. Below I created a picture just to show what I mean!

![SearchCatgeories](https://user-images.githubusercontent.com/66055492/119540206-78396d80-bd8d-11eb-832b-57aecbbb406c.png)

**Comment by LukasLoeffler** [comment]
Hello @TinusNL 

This is in fact already possible.
You have to pass a third parameter with the category:
this.editor.registerNodeType("NodeType", NodeType, "Category");

I forked the official sandbox and implemented this for the two example nodes:
[Example Sandbox](https://codesandbox.io/s/baklavajs-example-forked-qwqde)

**Comment by TinusNL** [comment]
Well, I guess I didn't search hard enough. Thanks though!
