### ISSUE TITLE
Group/Comment nodes

### ISSUE THREAD

**Issue by mmta41** [newcat/baklavajs#148]
Hi
thanks for the great job!
Do you have plan to add grouping/commenting nodes like noflo-ui or UE4 blueprints?

 
![ue4-blueprint-comment](https://user-images.githubusercontent.com/6301582/122896757-a3988380-d35e-11eb-96f4-20af6467d0b5.jpg)
![noflo-ui-group](https://user-images.githubusercontent.com/6301582/122896768-a85d3780-d35e-11eb-841e-abe6d9d18e2c.png)

**Comment by mmta41** [comment]
p.s: what is the solution to add type safe variables?

**Comment by newcat** [comment]
Yes, I am currently implementing this functionality in BaklavaJS v2. See also #99.
You can follow the current progress [here](https://github.com/newcat/baklavajs/projects/2) and on the [dev-v2.0 branch](https://github.com/newcat/baklavajs/tree/dev-v2.0)
