### ISSUE TITLE
Support for array inputs

### ISSUE THREAD

**Issue by potentially-null** [newcat/baklavajs#149]
Hey,

first of all, really cool project!

I was wondering if there is a way to define an input to which multiple outputs of the same type can be connected, resulting in an input array populated with the data of the connected outputs. 
I couldn’t find anything about this in the docs.

Thanks in advance

**Comment by newcat** [comment]
Hi, that's a great idea. Unfortunately, this feature doesn't exist out of the box in BaklavaJS v1. You'd need to write a customized [engine plugin](https://github.com/newcat/baklavajs/tree/master/packages/baklavajs-plugin-engine/src) for that. But I will put this feature on the roadmap for v2.

**Comment by newcat** [comment]
Implemented in V2: https://v2.baklava.tech/execution/dependency.html#multiple-connections-to-a-single-input
