### ISSUE TITLE
Engine Calculation Order Problems

### ISSUE THREAD

**Issue by pachacamac** [newcat/baklavajs#153]
As you stated your engine needs to have at least one node that has no output interfaces in order to automatically calculate a calculation order.

This can be improved by using e.g. [Kahn's Algorithm](https://en.wikipedia.org/wiki/Topological_sorting#Kahn's_algorithm) which is what I ended up doing.

By using Kahn's Algorithm the only constraint is that the graph can not contain cycles. Even not fully connected graphs (where you have dangling nodes / multiple not connected graphs) are supported and you can still calculate a calculation order. You also do not have to give hints to the algorithm as it simply finds the nodes that have no input connections and then traverses the graph/s from there.

**Comment by newcat** [comment]
I decided to implement this in v2 since this would be a breaking change.

However, if you set the `rootNodes` in the engine to all the nodes that do not have an outgoing connections (where no output is connected), the current algorithm should yield the same result as Kahn's algorithm.

**Comment by newcat** [comment]
Implemented in V2: https://v2.baklava.tech/execution/dependency.html
