### ISSUE TITLE
Multiline InputOption?

### ISSUE THREAD

**Issue by pachacamac** [newcat/baklavajs#156]
Is there an easy way to get a multiline textarea like input option going?

**Comment by newcat** [comment]
You can create your own option and use the existing `dark-input` class. It should mostly work for `textarea` elements as well.
Not tested, but the code for the option would look something like this:
```vue
<template>
    <div>
        <textarea
            class="dark-input"
            :value="value"
            :placeholder="name"
            @input="$emit('input', $event.target.value)"
        >
    </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";

@Component
export default class TextareaOption extends Vue {
    @Prop({ type: String, default: "" })
    value!: string;

    @Prop({ type: String })
    name!: string;
}
</script>
```

Afterwards you can register the option using [`registerOption`](https://newcat.github.io/baklavajs/#/node-options?id=options-in-the-viewplugin)
