### ISSUE TITLE
v2 Release

### ISSUE THREAD

**Issue by matthewdaviesflyt** [newcat/baklavajs#157]
Hi Frederik,

Do you have a rough date for the v2 release?

Thanks

Regards
Matthew

**Comment by newcat** [comment]
Hi Matthew,

unfortunately I am quite limited on time at the moment so I can't develop as fast as I want to. This also means that it is hard to estimate, when v2 will be released.

Currently I am planning to release Alpha and Beta versions of v2 towards the end of this year and then release a stable version at the beginning of next year. But I originally wanted to have v2 ready for the beginning of this year, so take my estimations with a grain of salt :wink: You can follow the current progress [here](https://github.com/newcat/baklavajs/projects/2)

If you are interested in using Baklava with Vue 3, check out #135.
