### ISSUE TITLE
Listening event of node selection

### ISSUE THREAD

**Issue by florianleux** [newcat/baklavajs#160]
Hello

I was wondering if there is any way to catch the selection of node (when you click on it in the editor and outline it).
I looked into both .events and .hooks but did not find anything related to this event.

The doc does not mention any way to do it, is it even possible ?

Thanks for your help and you very good work on this project !

**Comment by newcat** [comment]
It is possible, but with a little bit of a workaround:

1. Add `ref="editor"` (or whatever name you want the ref to have) to the `<baklava-editor>` element in the HTML like this:
```html
<baklava-editor ref="editor" :plugin="viewPlugin" />
```

2. Now you can watch the `selectedNodes` change:
```js
mounted() {
    this.$watch("$refs.editor.selectedNodes", () => {
        if (!this.$refs.editor) {
            return;
        }
        console.log(this.$refs.editor.selectedNodes.map(n => n.id));
    });
}
```

I have a full example here: https://codesandbox.io/s/baklavajs-example-selectevent-1klxj?file=/src/App.vue

And thanks for the kind words, appreciate it :)
