### ISSUE TITLE
Extending Editor vue file

### ISSUE THREAD

**Issue by florianleux** [newcat/baklavajs#165]
Hello there,

I'm really enjoying baklava in a project currently and was wondering if there is any possibility to extend the Editor vuefile in the same way we do it for viewPlugin components (Node, Minimap, NodeInterface etc...)

I have succeeded to extend Editor vue template in a new vue file (by importing  {Editor} from "@baklavajs/plugin-renderer-vue";) but I did not succeed to use this custom template in my Editor class.

Do you have any tips to do it (if its possible ?) 

I hope thats my question is clear enough !

Thanks again for your wonderful work on this lib.

florian

**Comment by newcat** [comment]
Unfortunately, there is no easy way to modify the editor template in Baklava V1. Depending on what you want to do, you could do some CSS trickery. For example, if you want to display an overlay, you can use `position: absolute` to position the overlay inside the editor (like I did in the [online demo](https://codesandbox.io/s/baklavajs-example-jyc6f?file=/src/HintOverlay.vue)).

**Comment by newcat** [comment]
I will close this for now; if you have further questions feel free to reopen the issue.
