### ISSUE TITLE
Dynamic Node construction

### ISSUE THREAD

**Issue by krish-adi** [newcat/baklavajs#169]
Hey there! 

Firstly, thanks for building this ! Awesome work...  🚀

So to my question, I want to be able to dynamically create a node. As in, I would like the user to enter a variable (ex. number of input interfaces) and create a node with that many input interface. 

I thought I could make a dynamic class constructor like this:

`DynamicNode.js`
```js
import { Node } from "@baklavajs/core";

export class DynamicNode extends Node {
    type = "DynamicNode";

    constructor({ InputsInfo, OutputsInfo }) {
        super();
        InputsInfo.forEach((input) => {
            this.addInputInterface(input.name, "NumberOption", 0);
        });
        OutputsInfo.forEach((output) => {
            this.addOutputInterface(output.name);
        });
    }
}
```

And, use it in the editor this way:

`BlockEditor.vue`
```vue
...
<script>
export default {
    ...
    data() {
        return {
            ...
            InputsInfo: [{ name: "Block In 1" }, { name: "Block In 2" }],
            OutputsInfo: [{ name: "Block Out 1" }, { name: "Block Out 2" }],
        };
    },
    created() {
        ...
        let DNode = new DynamicNode({
            InputsInfo: this.InputsInfo,
            OutputsInfo: this.OutputsInfo
        });
        this.editor.registerNodeType("DynamicNode", DNode);
    },    
};
</script>
```

The node is getting registered in the context menu, but I cannot add it to the canvas. 

```error
TypeError: nt is not a constructor
    at VueComponent.EditorView.onContextMenuClick (index.js?0c30:1703)
```

Checking the type of DNode, it was `object` and not a class constructor. How do I solve this?

**Comment by krish-adi** [comment]
So, I played around a bit and ...

```
import { NodeBuilder } from "@baklavajs/core";

export function BlockBuilder({ InputsInfo, OutputsInfo }) {
    const Block = new NodeBuilder("DisplayNode");
    Block.setName("Block")
    InputsInfo.forEach((input) => {
        Block.addInputInterface(input.name, "NumberOption", 0);
    });
    OutputsInfo.forEach((output) => {
        Block.addOutputInterface(output.name);
    });
    return Block.build();
}
```

```
const Block1 = BlockBuilder({
      InputsInfo: this.InputsInfo,
      OutputsInfo: this.OutputsInfo,
    });

this.editor.registerNodeType("Block1", Block1);
```

... this seems to work.

**Comment by newcat** [comment]
Sorry for taking so long to reply. This is indeed the way I'd have suggested to implement it. Just a quick heads up: Without some additional logic, these nodes don't save&load correctly. If you don't use saving and loading, it's not an issue, but if you do, make sure to implement custom logic in the `save` and `load` hooks: https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-playground/src/AdvancedNode.ts
