### ISSUE TITLE
[Documentation] Broken link

### ISSUE THREAD

**Issue by MSoup** [newcat/baklavajs#171]
While going through the documentation, I came across this section:

Additional Options
You can pass additional options to your nodes, node interfaces or node options that can be used by the renderer-vue plugin. These additional options can also be used when you use [custom components.](https://newcat.github.io/baklavajs/#/../styling)

It's about halfway down the page at this url https://newcat.github.io/baklavajs/#/plugins/view

I just wanted to report the broken link. Thanks a lot for your time and I really love this project.

**Comment by newcat** [comment]
Fixed, thanks for reporting!
