### ISSUE TITLE
Extending nodes to support attachment of images

### ISSUE THREAD

**Issue by MSoup** [newcat/baklavajs#173]
I'd like to be able to add image data into my nodes, such as graph outputs from calculations of previous nodes, or even just image data to make flows easier to understand. 

Is there an easy way to do this? I was hoping I could just look at the mathnode example and modify it to be able to fit images, but I lack the knowhow. Would love any advice.

**Comment by newcat** [comment]
Not sure if I understand your issue 100% correctly.

If you mean adding images to nodes, you can do it via a custom option. I have created such an option here: https://github.com/newcat/LedMusic3/blob/master/src/graph/options/PeakOption.vue

It is not directly showing an image, but instead showing a canvas where I draw a bar on it depending on the value of the option (https://raw.githubusercontent.com/newcat/LedMusic3/master/demo.png can be seen in the "Peak" node). Of course you can just replace the `<canvas>` element with an `<img>` element.

**Comment by MSoup** [comment]
Thanks, I'll give this a try and report back in a few days. Right now I seem to have run into an issue where vue typescript wasn't installed initially when setting up my project, so I'm unable to import the PeakOption.vue file. Need to figure that out first :)

Sorry if I ask a lot of questions, I really like this package but I'm not experienced enough to implement a lot of the things I want to do, especially while keeping components loosely coupled!

**Comment by newcat** [comment]
I guess this issue can be closed with the example here https://github.com/newcat/baklavajs/issues/174#issuecomment-999865334 - if not, feel free to reopen.
