### ISSUE TITLE
Node custom properties - how to work with existing structure?

### ISSUE THREAD

**Issue by MSoup** [newcat/baklavajs#175]
Hi again. I'm so sorry to make multiple posts.

I see in your node definition file (node.d.ts) that there is a state field, defined here

```
    /** Use this property to save additional state of the node */
    state: Record<string, any>;
```

Is this where I can pass in extra data? 

For example, what I want to do is give nodes information such as:
- a file name
- a reference to the next node it connects to
- a reference number
- a description of the node

I also see a options property, but the documentation you made makes me believe that options are for setting things like sliders, input fields, etc within the node "body". 

If this is where I pass in extra data, I guess my next question is that it takes in a Record object? I can't find info on how Record objects are constructed in order to proceed.

Thanks a lot for your time

**Comment by LukasLoeffler** [comment]
I am not sure if it it's the right way to do it, but you can achieve your goal with custom options which are not rendered but carry data.

**Comment by MSoup** [comment]
Oh that's an interesting way to do it. I used "state" but I feel like I'm breaking all sorts of rules ;)

**Comment by newcat** [comment]
`Record<string, any>` is basically just TypeScript speech for "any JavaScript object" ;)
In your case, the "proper" way to do it would indeed be to use the `state` property. Using a hidden option and saving the data in the option value does work as well, but if it's just metadata for the node instance I feel using `state` is more appropriate.
