### ISSUE TITLE
Trying to understand the inner workings of the codebase: where is "position" defined?

### ISSUE THREAD

**Issue by MSoup** [newcat/baklavajs#176]
I was looking at the example codepen shared here https://codesandbox.io/s/baklavajs-example-jyc6f?file=/src/App.vue:2032-2040

And I see a method that takes in coordinates along with a Node type:

```
    methods: {
        addNodeWithCoordinates(nodeType, x, y) {
            const n = new nodeType();
            this.editor.addNode(n);
            n.position.x = x;
            n.position.y = y;
            return n;
        }
    }
```

I also see that node instances have positions defined when looking at nodes in the web dev tools. However, when I do a search where Nodes are defined (node.d.ts) I do not see "position". I also cannot find "position" when I search all my libraries related to baklavajs. 

Does anyone know where position comes from? I think learning about this will help me understand a lot more about inheritance, perhaps. 

The reason I ask originally came from me trying Typescript for fun, but having trouble defining types properly in order to effectively use it. For example, in my Editor.vue I have 

```
        getPosition(node) {
            return [node.position.x, node.position.y]
        },
```

but when I try to define node like
```
        getPosition(node: Node) {
            console.log(node)
            return [node.position.x, node.position.y]
        },
```

TypeScript tells me that Node does not have "position". I saw that too by looking into node.d.ts. But.. then how does it exist?

**Comment by LukasLoeffler** [comment]
I am not sure if it answers your question, but you may have a look at the [Node.vue](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-renderer-vue/src/components/node/Node.vue) file.

```
    get styles() {
        return {
            top: `${this.data.position.y}px`,
            left: `${this.data.position.x}px`,
            width: `${this.data.width}px`,
        };
    }
```

The getStyles method is used by the node container to destinguish the position of the node in the editor.

```
    handleMove(ev: MouseEvent) {
        this.selectedNodeViews.forEach((elem: any) => {
            if (elem.draggingStartPoint) {
                const dx = ev.screenX - elem.draggingStartPoint.x;
                const dy = ev.screenY - elem.draggingStartPoint.y;
                elem.data.position.x = elem.draggingStartPosition.x + dx / elem.plugin.scaling;
                elem.data.position.y = elem.draggingStartPosition.y + dy / elem.plugin.scaling;
            }
        });
    }
```

This part shows how the position is set after moving the node.

**Comment by MSoup** [comment]
Thank you for your comments. They're always really helpful!

One thing that confuses me is that "position" is not defined in Node.vue either. Is this an attribute that just exists on the DOM? 

If I want to make a helper function, such as the above
```js
getPosition(node) {
            return [node.position.x, node.position.y]
        }
```

How would I convert this into typescript? If I type node: Node, it says that Node does not have position, but I am able to access the position properties of nodes!

**Comment by newcat** [comment]
Indeed, this is an issue with BaklavaJS version 1, which isn't really designed around TypeScript (even though it was written in TS from the start... I learned a thing or two along the way 😄 )

The position comes from here: https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-renderer-vue/src/viewPlugin.ts#L79

As you can see, I also cast the node to `IViewNode` which is an interface that tells TypeScript about the additional properties like `position`, etc. on the node.

You can import `IViewNode` like this:
```ts
import { IViewNode } from "@baklavajs/plugin-renderer-vue/dist/baklavajs-plugin-renderer-vue/types";
```

and then do the cast in your code as well. With that, you should be able to get rid of the type problems around `node.position`.

**Comment by MSoup** [comment]
@newcat Oooh!! Thank you so much!

Using BaklavaJS is teaching me much more than any course I've taken ;) The freedom to be able to build my own node generators, make my own Node classes, etc feels like I'm playing a video game.

**Comment by newcat** [comment]
Yes, either you do
```ts
getPosition(node: IViewNode): [number, number] {
    return [node.position.x, node.position.y]
}
```
but that might cause errors somewhere else.

The safe option would be:
```ts
getPosition(node: Node): [number, number] {
    const n = node as IViewNode;
    return [n.position.x, n.position.y]
}
```

Or to make it a bit more verbose:
```ts
getPosition(node: Node): [number, number] {
    return [(node as IViewNode).position.x, (node as IViewNode).position.y]
}
```

**Comment by MSoup** [comment]
TS is yelling at me when I try to convert Node to IViewNode

```
Conversion of type 'Node' to type 'IViewNode' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

**Comment by newcat** [comment]
That is interesting, why does it work in the ViewPlugin then? 😁

Anyway, in that case you can do `node as unknown as IViewNode`

**Comment by MSoup** [comment]
Solved :)

At this point the questions don't have to do with BaklavaJS and have more to do with TypeScript, so I'm really sorry for taking up your time. You've been wonderful.

I'm still struggling a little bit with casting--I never know when to use `Node`, `INode`, `IViewNode`, or `any`

For example
```js
        makeNode(nodeName: string, nodeType: any, options: any = {}) {
            const n: IViewNode = new nodeType()
            n.name = nodeName
            if (options.hasOwnProperty("DisplayText")) {
                n.setOptionValue("DisplayText", options.DisplayText)
            }
            
            n.customClasses = n.name
            this.editor.addNode(n)
            return n
        },
```

Regarding nodeType, if I set it to `any`, it works because it just becomes JS without any type checking.

But if I set NodeType to Node, INode, or IViewNode, I get the following error:
```
(parameter) nodeType: INode
This expression is not constructable.
  Type 'INode' has no construct signatures.
```

Also, when I set n to IViewNode, I am allowed to make a `new nodeType()`,  (in fact, it must be IViewNode because I am setting a custom class and it is only defined there). 

However, this.editor.addNode takes in a node!

Therefore I get this error:
```
Argument of type 'IViewNode' is not assignable to parameter of type 'Node'.
  Type 'IViewNode' is missing the following properties from type 'Node': addInputInterface, addOutputInterface, removeInterface, addOption, and 2 more.
```

I cannot change what addNode takes, since it is in editor.d.ts. 

Is there anything I can do here?

**Comment by newcat** [comment]
Your `nodeType` would be `new () => Node` in this case.

Then I'd just use the `IViewNode` for setting the view-related properties like this:
```ts
(n as unknown as IViewNode).customClasses = n.name
```

This separation between interfaces and actual implementations has historical reasons and won't exist in Baklava V2 anymore, but for now we have to live with it unfortunately.
