### ISSUE TITLE
rename node on addition

### ISSUE THREAD

**Issue by krish-adi** [newcat/baklavajs#179]
Is it possible to change the name of the node once it is added to the editor?

Expected output:

If the user adds a 'MathNode', the results name of the node to be 'MathNode-1' or with a random string 'MathNode-random-string'.

**Comment by LukasLoeffler** [comment]
Just add  _this.name = Math-${Math.random()};_ to the constructor.
I forked the sandbox to demonstrate it: [Link](https://codesandbox.io/s/baklavajs-example-forked-q7tl7)

**Comment by krish-adi** [comment]
Ah! That works... 

Is there also hook to listen to when a node is added?

**Comment by newcat** [comment]
Thanks for the quick support @LukasLoeffler :)
