### ISSUE TITLE
Node Snapping

### ISSUE THREAD

**Issue by ThePixelDeveloper** [newcat/baklavajs#184]
Self-explanatory, but the ability to be able to snap the nodes to the underlying grid would be a nice addition. 

I'm constantly vertically aligning nodes so the lines are nice and crisp.

**Comment by newcat** [comment]
Hey, sorry for the late reply. That would indeed be a nice feature. I think this might also be related to #172.

Unfortunately I am quite busy at the moment so I am not sure, when I am able to implement it. But I'll do it as soon as I have some time.

**Comment by newcat** [comment]
[Implemented](https://newcat.github.io/baklavajs/#/plugins/view?id=node-snapping) in v1.10.0
