### ISSUE TITLE
Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by florentmaye** [newcat/baklavajs#188]
Hi,

I'm trying to run the getting started example:

```

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BaklavaJS Vanilla Example</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/baklavajs/dist/styles.css">
</head>
<body>

    <div style="width:90vw;height:90vh">
        <div id="editor"></div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="https://cdn.jsdelivr.net/npm/baklavajs/dist/index.js"></script>
    <script>
        const plugin = BaklavaJS.createBaklava(document.getElementById("editor"));
        const editor = plugin.editor;

        const myNode = new BaklavaJS.Core.NodeBuilder("My Node")
            .addInputInterface("My Interface")
            .build();
        editor.registerNodeType("My Node", myNode);
    </script>

</body>
</html>


```
source: "https://newcat.github.io/baklavajs/"

But I'm already having an issue :

    index.js:6365 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at extendStatics (index.js:6365:12)
    at __extends (index.js:6369:5)
    at index.js:7329:68
    at Object.<anonymous> (index.js:7340:2)
    at __webpack_require__ (index.js:6250:30)
    at Object.<anonymous> (index.js:7316:194)
    at __webpack_require__ (index.js:6250:30)
    at Object.<anonymous> (index.js:7929:100)
    at __webpack_require__ (index.js:6250:30)

And then the lib is not loaded correctly

    Uncaught ReferenceError: BaklavaJS is not defined

Am I doing something wrong?

Thank you for your help

**Comment by newcat** [comment]
Thanks for raising this issue! Vue has changed its default version from v2 to v3 recently. When you change the script src to `https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js` it works again. I have updated the documentation accordingly.
