### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by TomYeoman** [newcat/baklavajs#195]
Hi! 

First off I'd like to give my thanks for creating this library, we're enjoying using it on our project. 

I would like to discuss some performance issues we're having, potential fixes, and whether these are something you may consider being part of the core library offering.

Initially, I'd like to share a screenshot of our graph, so you can get an idea of what we're working with. 

![image](https://user-images.githubusercontent.com/14075632/166656718-ca6e20b2-fa0b-4909-b23f-34bfc31eef1c.png)

Now, we're facing several issues:
- Load time takes 1min+ in Firefox, and even longer in chrome.
- Connecting nodes on the edges, can take 15-20s+ on chrome (although stay within a couple of seconds in Firefox strangely).

I've boiled this down to the fact that `CalculateOrder` function, [which runs every time we](https://github.com/newcat/baklavajs/blob/e4ce5c4e355652de421db822f31a73a48dc35831/packages/baklavajs-plugin-engine/src/engine.ts#L162) `CheckConnection`, is run:
- Every time we load a graph, the library attempts to [re-add every node's](https://github.com/newcat/baklavajs/blob/e4ce5c4e355652de421db822f31a73a48dc35831/packages/baklavajs-core/src/editor.ts#L129) connection and this function gets called for every node X>Y
- Every time we try to connect 2 node's (after load).

Here's what happens every time a node is connected:
- [We run a DFS, with cycle check for every node with no outputs](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-engine/src/nodeTreeBuilder.ts#L37) (E.G for this particular graph that means we're running a DFS 37 times across the graph once nearly every connection is added, for every output node we have) 
- Once we have the full path for each output node via the DFS, [run a BFS across the node's](https://github.com/newcat/baklavajs/blob/e4ce5c4e355652de421db822f31a73a48dc35831/packages/baklavajs-plugin-engine/src/nodeTreeBuilder.ts#L38), so the baklava engine can calculate the order to run node's.

---
**Suggested changes?**

1. Allow the `CalculateOrder` check for each node to be optional when calling load, it doesn't seem like there's always a need to do that when we're already running the checks every connection we add. This change alone make's load run in <1s for FF/Chrome

2. Decouple the generation of baklava node execution order, from the cycle checking.

Myself (and perhaps others) are actually just using Baklava as a graph rendering Vue library (then using the save/load feature when done, and running the graph on the server using our own execution logic). 

If we were to remove the BFS check / make it optional via some sort of opt in engine config parameter, it speeds up node connection (worse case) from ~20s to ~2s in chrome. It must be noted I am noticing weird behaviour in the fact Firefox seems to be able to handle the [stack generated here](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-engine/src/nodeTreeBuilder.ts#L41) of ~5mil items on some connections extremely fast, compared to chrome which completely chokes. 

---

Would appreciate any thoughts you have regarding the above! 

Thanks

**Comment by newcat** [comment]
I have to admit, I have never tested this lib on graphs this large. So, unsurprisingly, the very handcrafted and probably far from optimal cycle detection does cause these performance issues (although I guess there are a lot of other things that aren't really optimized for large graphs).

If you only need the cycle checking, it's probably best to not use the engine plugin and instead provide your own plugin that does the cycle check on the `checkConnection` event (basically [this](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-engine/src/engine.ts#L81-L85)).

It's probably too late for Baklava v1, but for v2 I'll try and also consider performance on larger graphs when implementing logic like this.

**Comment by TigerHix** [comment]
> Myself (and perhaps others) are actually just using Baklava as a graph rendering Vue library (then using the save/load feature when done, and running the graph on the server using our own execution logic).

Second this!

**Comment by newcat** [comment]
I think I will just add a `editor.loading` flag, which indicates whether the editor is currently in the process of loading nodes and connections. So in your `checkConnection` event you can then directly return if `editor.loading === true`.

This way I don't have breaking API changes and it also usable in other areas.

**Comment by TomYeoman** [comment]
That would be fantastic thanks so much. I will try and contribute back a plugin which strictly does a cyclic check on connection add. 

Curiously which release is this likely to be shipped under (current, or V2)?

**Comment by newcat** [comment]
This is for v1 (which I guess you are using). I will try to port all the features from v1 to v2 though.

**Comment by newcat** [comment]
Implemented in v1.10.0
