### ISSUE TITLE
The connection line is missing

### ISSUE THREAD

**Issue by Halinen** [newcat/baklavajs#196]
I would like to deploy my website with that [web template](https://github.com/PanJiaChen/vue-admin-template), and I want to use this library because the screenshot in README is so beautiful.

But I have met a problem. The connection line doesn't show in that web template. And I don't know how to solve it.

![image](https://user-images.githubusercontent.com/36531291/167251784-a00f1d37-7faf-43f2-b9d0-7ec72806f998.png)

**Comment by newcat** [comment]
That is very weird. The connections are based on SVG - can you check whether there are any CSS styles that interfere with the SVG or its child elements?

**Comment by anders-rv** [comment]
Hi, I just encountered this as well. It is actually reproducible in the online demo @ https://codesandbox.io/s/baklavajs-example-jyc6f by changing the baklavajs version from 1.8.2 -> 1.9.3+

**Comment by LukasLoeffler** [comment]
I also tested against this bug and found out that this issue only occurs with vue version < 2.6.13.
v2.6.13+ just works fine.
