### ISSUE TITLE
Is there a way to rewrite "Connection" rules?

### ISSUE THREAD

**Issue by Halinen** [newcat/baklavajs#198]
Hi,

I would like to make specific `Connection` rules. For example, node A can only connect to Node B, and if it wants to connect to Node C, the state of `Connection` should be `isInDanger`.

**Comment by newcat** [comment]
Yes, you can use the `editor.events.checkConnection` event:

```ts
editor.events.checkConnection.addListener(this, (c) => {
  // return false if the connection is not allowed
});
```

**Comment by Halinen** [comment]
Thanks for the quick support😊

**Comment by Halinen** [comment]
I'm confused with another problem. 

Is there a way to set the `disabledFunction` property of the items in `contextMenu`?

I would like to make that some Nodes can only be added for once.

**Comment by Halinen** [comment]
I have tried this way, and the item in `contextMenu` indeed becomes `disabled`. 
```
this.viewPlugin.editor.events.beforeAddNode.addListener(this, (node) => {
      this.$refs.editor.contextMenu.items[0].submenu[2].disabled =
      (this.editor._nodes.filter(p =>
      p.name.indexOf(this.$refs.editor.contextMenu.items[0].submenu[2].label)!==-1)).length >= 0
});
```
But it seems not functionally `disabled`...

![issue](https://user-images.githubusercontent.com/36531291/168996805-ab4bf9f5-ab50-4061-8bd9-78fc37523bbb.gif)

**Comment by Halinen** [comment]
I have solved it 😀

```
checkNodeCount(nodename) {
      let nodesOnEiditor = toRaw(this.$refs.editor.nodes)
      let flag = true
      nodesOnEiditor.forEach((val)=>{
        if(nodename == "myNodeName" && val.name == "myNodeName"){
          flag = false
          return
        }
      })
      return flag
}
 
```


```
this.viewPlugin.editor.events.beforeAddNode.addListener(this, (node) => {

      if(this.checkNodeCount(node.name)){
        if(node.name == "myNodeName" ){
          //contextMenu disabled 
          this.$refs.editor.contextMenu.items[0].submenu[2].disabled = true
        }
        return true
      }
      else{
        return false;
      }
    });
```

**Comment by LukasLoeffler** [comment]
Congrats that you solved it by yourself!
Just beeing nitpicky here:
You use the array.some() method instead the array.forEach() loop.
The array.some() method checks if the provided statement matches at least once on one of the elements in the array.

```js
let flag = !nodesOnEditor.some((val)=>nodename == "myNodeName" && val.name == "myNodeName"))
```
