### ISSUE TITLE
Moving Nodes is buggy in Chrome

### ISSUE THREAD

**Issue by newcat** [newcat/baklavajs#20]
When moving a node in Chrome, it moves at a different speed compared to the cursor.

**Comment by newcat** [comment]
This is likely an issue with DPI scaling as it seemingly doesn't happen on monitors without DPI scaling

**Comment by code-is-art** [comment]
I think this should be reopened as this doesn't work for me and I have to revert it to work on both Chrome and Firefox on OSX . Maybe this should be an optional setting.

**Comment by newcat** [comment]
Could be something to do with this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=162187

What value does `window.devicePixelRatio` have on your system?

**Comment by code-is-art** [comment]
I get 2 on Safari, Chrome and Firefox latest versions.

**Comment by LukasLoeffler** [comment]
I can reproduce the issue by enabbling the windows screen scaling.
As already stated, this only affects Chrome not Firefox.
![image](https://user-images.githubusercontent.com/24526399/108490002-85ccec00-72a2-11eb-842e-8679256d0612.png)
