### ISSUE TITLE
Dynamically change items for SelectOption

### ISSUE THREAD

**Issue by KimiNoNawa1610** [newcat/baklavajs#206]
Hi, Team.
Thank you so much for the wonderful work.

I have a question. Is there any way that we can change the items of SelectionOption on runtime.

For example, I have two Options. I want to change the items of the second option based on the value of the first Option.

Thank you so much.

**Comment by newcat** [comment]
Yes you can do it like this:
```javascript
const operationOption = this.addOption("Operation", "SelectOption", "Add", undefined, {
  items: ["Add", "Subtract"]
});

// to update the items:
operationOption.items = ["Multiply", "Divide"];
operationOption.events.updated.emit();
```

**Comment by minecraft2048** [comment]
@newcat Can you please explain more about this code? How do you call `operationOption.events.updated.emit();` when another option is updated?
