### ISSUE TITLE
How to disable context menu.

### ISSUE THREAD

**Issue by imshubhamkumar** [newcat/baklavajs#207]
How to disable context menu. I don't want to use context menu an in the given document i did not find any option to disable context menu

**Comment by newcat** [comment]
Didn't test it, but you could try setting the ContextMenu component to a custom empty Vue component: https://newcat.github.io/baklavajs/#/styling?id=hardcore-customization

**Comment by andreibosco** [comment]
> Didn't test it, but you could try setting the ContextMenu component to a custom empty Vue component: https://newcat.github.io/baklavajs/#/styling?id=hardcore-customization

Just tested it on vue3 and that suggestion works 👍
