### ISSUE TITLE
scss color modifying problem

### ISSUE THREAD

**Issue by ThomasXIONG151215** [newcat/baklavajs#210]
I tried following the Styling tutorial to customize background color but nothing changes when displaying on codesandbox. 

I created a test.scss and imported variables.css as well as styles.css then I started modifying variables.
Before saving I imported test.scss directly into the main.js. Is this how Im supposed to do it?

**Comment by newcat** [comment]
I updated the docs, they had wrong paths. Can you try again if it works now?

**Comment by newcat** [comment]
Closing this, feel free to reopen if the issue still persists
