### ISSUE TITLE
Floating connections when using node snapping + editor load

### ISSUE THREAD

**Issue by mike-northsail** [newcat/baklavajs#211]
When loading from a saved state, the simple snapping provider causes existing connections to float away from their respective interfaces when rearranging the nodes.

New connections appear to be unfazed  though.

It happened at various grid sizes too, 10x10, 20x20, 30x30 etc. 

https://newcat.github.io/baklavajs/#/plugins/view?id=node-snapping

**Comment by KimiNoNawa1610** [comment]
I Have the same problem. It Happened when I moved from 1.8.7 to the new 1.10.1
![Screenshot from 2022-09-08 14-35-50](https://user-images.githubusercontent.com/48186215/189229790-5a66dbbe-d8bd-409f-8ace-464d18162af7.png)

**Comment by newcat** [comment]
Should be fixed with version [1.10.2](https://github.com/newcat/baklavajs/releases/tag/v1.10.2)
