### ISSUE TITLE
[documentation request]  Example project v2

### ISSUE THREAD

**Issue by AbCoding** [newcat/baklavajs#230]
Within the documentation could you include an example for v2. I was following the documentation to get a project setup for v2 and had trouble understanding how graph execution worked in code with the dependency engine. An example repo of code would be much appreciated.

**Comment by newcat** [comment]
Good point! I'll be working on creating a CodeSandbox for that, similar to the v1 sandbox. Currently, there are some issues with how the library is built and therefore I can't get it running on CodeSandbox. Once I figure out the issues and fix them, I'll post a link to the sandbox here.

**Comment by newcat** [comment]
CodeSandbox for v2 is now up: https://codesandbox.io/s/baklavajs-v2-example-zpfkec?file=/src/App.vue
