### ISSUE TITLE
Overriding components in V2

### ISSUE THREAD

**Issue by johnhkelley1** [newcat/baklavajs#231]
Hi, I'm trying to override the connection component in V2. The V1 documentation (https://newcat.github.io/baklavajs/#/styling?id=hardcore-customization) suggests this pattern:

`import MyNodeComponent from "MyNodeComponent.vue";
viewPlugin.components.node = MyNodeComponent;`

However I can't find any documentation for how to do this in the new version. Is this possible in V2? Thanks!

**Comment by newcat** [comment]
Good point, I completely forgot to document that. I created a new customization page in the docs: https://github.com/newcat/baklavajs/blob/dev-v2.0/docs/visual-editor/customization.md

The page will be deployed with the next beta release and then all links will be working. Also note that currently, the slot for connections is still called `connections` - with the next beta release it will be renamed to `connection` to match the other slot names.

**Comment by JosueGauthier** [comment]
Hello, 
I try to override a Node to make a hard custom node. 

I read the customization.md file but I have not well understand how to proceed. There is this [default component](https://github.com/newcat/baklavajs/blob/dev-v2.0/packages/renderer-vue/src/node/Node.vue) but how I implement it ? There are some links to ../utility and others, should I work with the source code instead. 

I am looking for an example but i found nothing that works with the V2. 

Thanks,
