### ISSUE TITLE
[v2] Visual editor node interfaces and connections not reactive

### ISSUE THREAD

**Issue by tehbiga** [newcat/baklavajs#233]
Just reporting some weirdness I'm seeing when trying to make really dynamic nodes with a dropdown option that changes the interfaces. If you want I can post some customizations I made to get it mostly working.

_Issues I ran into:_

* Removing and adding interfaces while a node component is already placed in the graph will not update the visuals at all
* Connection SVG elements orphaned when I modify the Vue Node component to make interfaces reactive

_Deeper explanation:_

I was able to get _some_ things working by replacing the Vue Node, but your save/load bug fix key counter is not accessible. Ignoring the loss of that fix it, making the interface property reactive and using `$forceUpdate`  turns the object maps into Proxy objects for Vue and breaks the connection removal on interface removal logic because objects are compared instead of identifiers. When manually removing all connections the graph is still not updated so the elements are stuck in view.

**Comment by newcat** [comment]
Yes, that caused me a lot of headaches as well. In general, whenever you use the node instance you get at or after `onPlaced` is called, you should get the reactive proxy. I am also currently working on a [DynamicNode](https://github.com/newcat/baklavajs/blob/dev-v2.0/packages/core/src/dynamicNode.ts) that should hopefully meet your needs. It is already mostly working, I only need to fix an issue when using a dynamic node together with the engine. The functionality should be included in the next beta release.

**Comment by newcat** [comment]
Dynamic nodes have been released in [v2.0.2-beta.3](https://github.com/newcat/baklavajs/releases/tag/v2.0.2-beta.3)
