### ISSUE TITLE
Allow to provide label to input and output interfaces

### ISSUE THREAD

**Issue by alexisrolland** [newcat/baklavajs#237]
Hello and thank you for open sourcing BaklavaJS! Your library is truly awesome.

I'd like to know if it is still under active development? And if so, would you have in plan to allow adding labels to input/output interfaces? This could allow to have unique names while displayed labels could be non unique... I have a use case where a node needs to have the same name for its input and output interfaces so right now it is not possible to do it.

Example of what I have now:
```js
  public constructor() {
    super();
    this.addInputInterface("Text Input", "", "", { type: "string" });
    this.addOutputInterface("Text Output", { type: "string" });
  }
```

Example of what I would like to have (which breaks the node logic when doing `this.getInterface("Text").value` because both interfaces have the same name):
```js
  public constructor() {
    super();
    this.addInputInterface("Text", "", "", { type: "string" });
    this.addOutputInterface("Text", { type: "string" });
  }
```

Alternatively, it could also make sense to have two functions `getInputInterface` and `getOutputInterface` rather than just one `getInterface`.

Thank you

**Comment by newcat** [comment]
This is possible, but apparently, I didn't document it anywhere. You can pass the additional property `displayName` when creating options/interfaces. I have added the [documentation](https://newcat.github.io/baklavajs/#/custom-nodes?id=overriding-the-name-of-a-node-interface-or-node-option) now, thanks for raising this issue.
