### ISSUE TITLE
Build node types dynamically from data in a database

### ISSUE THREAD

**Issue by alexisrolland** [newcat/baklavajs#239]
Hello,
I have checked the documentation but could not find an answer to my question, so I'm asking here.

I would like to build and register node types dynamically using data contained in a database. I have created some node template using the [Class approach to custom nodes implementations](https://newcat.github.io/baklavajs/#/custom-nodes?id=class). My problem  is that properties of the class are hard coded in the class... for instance the `name` and `type` properties:

```js
import { Node } from "@baklavajs/core";

export class MathNode extends Node {
    type = "MathNode";
    name = "Math";

    constructor() {
        ...
    }
```

At the moment I register this node type with: `this.editor.registerNodeType("Math", MathNode);`

I would like to know if it is possible to "parametrize" the class and provide arguments for the `name` property and for some other custom properties when registering the node type?

Thanks a lot for your inputs.

**Comment by newcat** [comment]
Sure, you can wrap the class in a function that generates the class dynamically, like this:

```js
function createNodeType(nodeType, defaultName) {
  return class extends Node {
    constructor() {
      this.type = nodeType;
      this.name = defaultName;
      // ... create interfaces and options dynamically
    }
  }
}
```

and then do

```js
this.editor.registerNodeType("Math", createNodeType("Math", "My Math Node"));
this.editor.registerNodeType("Output", createNodeType("Output", "My Output Node"));
```

Of course, this only makes sense if the generated node types are always the same, e. g. if a node of type "Math" always has the same interfaces and options. Otherwise, loading and saving will be broken.
