### ISSUE TITLE
Connections are not rendered in the expected location 

### ISSUE THREAD

**Issue by MathArtist2** [newcat/baklavajs#260]
Hello every body.

Connections are not rendered in the expected location 

As shown in the image
![image](https://user-images.githubusercontent.com/12837010/217707979-4cdcf095-20d8-4286-b35b-faf4d108e267.png)

This project is only a new vue app with the basic example editor and example node in it

  "baklavajs": "^2.0.2-beta.3",
  "vue": "^3.2.45",

Is it a bug? or does it need some additional configuration?

Best regards

**Comment by MathArtist2** [comment]
The problems seem to be related interface.offsetTop property
![image](https://user-images.githubusercontent.com/12837010/218238217-1a390c0f-0e4d-46b4-bc8d-07a0d57b7b88.png)

**Comment by newcat** [comment]
Apparently, the default styles that come with a newly created Vue 3 app interfere with Baklava somehow. If you remove the `import './assets/main.css'` line in your `main.js` it should work.
