### ISSUE TITLE
More details in the documentation

### ISSUE THREAD

**Issue by GrimPixel** [newcat/baklavajs#268]
Hi, I am not familiar with JS, so I am confused with the documentation. I haven't figured out how to get it running like the demo. Could you add details to the documentation?

**Comment by GrimPixel** [comment]
In “Getting Started”, such as why there is an HTML before installing it, what to modify in “So you have to modify them slightly to work.”

**Comment by newcat** [comment]
Not sure how to make this more clear - I added some color coding, maybe that helps?

**Comment by GrimPixel** [comment]
Thank you for doing that. I just had no idea how to run JavaScript programs. It is already good for those who know it.
