### ISSUE TITLE
ButtonInterface

### ISSUE THREAD

**Issue by Thevetat** [newcat/baklavajs#272]
Documents are a bit sparse on how to use the ButtonInterface.  Not sure if it should go in inputs or outputs.  Trying to just have a simple, on click convert input to 'Hello World' Type node and display as an output.  Any help or direction would be greatly appreciated.

**Comment by newcat** [comment]
Not sure if I fully understood the issue - do you want to start a calculation when the button is clicked? The button itself can be input or output, doesn't really matter. Also, it simply calls the callback you provide when instantiating the interface; it doesn't have any additional logic.
