### ISSUE TITLE
Trigger context menu

### ISSUE THREAD

**Issue by davidavz** [newcat/baklavajs#276]
Hi 👋

What is the best way to trigger the context menu ? 

Let's say I have a custom Vue component which is a button, I want to be able to show the context menu on click event.
And ideally I would like that the new position of the menu to be the position of my button (on the grid area)

Thanks

**Comment by newcat** [comment]
Assuming you use the context menu like this:
```vue
<template>
  <button @click="onBtnClick">Click me</button>
  <ContextMenu
    v-model="contextMenuData.show"
    :x="contextMenuData.x"
    :y="contextMenuData.y"
    :items="contextMenuData.items"
    flippable
    @click="onContextMenuClick"
  ></ContextMenu>
</template>

<script setup>
import { ContextMenu } from "baklavajs";
const contextMenuData = ref({
  show: false,
  x: 0,
  y: 0,
  items: [{ label: "Foo", value: "foo" }, { label: "Bar", value: "bar" }]
});

function onClick(ev) {
  contextMenuData .value.show = true;
  contextMenuData .value.x = event.offsetX;
  contextMenuData .value.y = event.offsetY;
}
</script>
```

This is not tested and you might need to fiddle with the coordinates and CSS but in general that's how I'd do it

---

Actually, after writing all this, I am not sure if I understood your question correctly. Do you want to display your own custom 
context menu or do you want to trigger the existing context menu for adding nodes when clicking on your button?

**Comment by davidavz** [comment]
Thanks for the response. 
I would like to trigger the existing context menu.

**Comment by newcat** [comment]
I see. Not sure if that is easily possible. You could try getting a [ref](https://v2.vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements) to the `Editor` component which has the [`openContextMenu`](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-renderer-vue/src/components/Editor.vue#L353) function. If you call that with the click event of the button it should open the context menu. But you might need to fiddle with the coordinates. And you need a way to access the editor ref inside your nodes, maybe with a global variable or something.
