### ISSUE TITLE
Accessing Node Properties and IDs in sidebar

### ISSUE THREAD

**Issue by tpfau** [newcat/baklavajs#277]
Is there any better way to access the node data in the sidebar besides using $attrs ?
This might be my lack of understanding of vue and typescript but I can't really get access to it any other way.

**Comment by newcat** [comment]
When creating a Vue component that is displayed in the sidebar, you can explicitly define props that the `$attrs` are mapped to. For example:

```vue
<template>
    <h1>{{ node.title }}</h1>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
    props: ["node"],
});
</script>
```

You can also type props, see [Vue docs](https://vuejs.org/guide/typescript/options-api.html#typing-component-props) for more information
