### ISSUE TITLE
Custom connections, nodes and more...

### ISSUE THREAD

**Issue by mioe** [newcat/baklavajs#278]
hello, i'm developing a chat bot editor (vue3)
https://github.com/mioe/flow-chat-bot-editor

I need to know if these functions are possible:
- [x] custom connections (change line ending)
- [x] custom nodes (change locations ports)
- [x] change the relationship between nodes 1 to 1
- [x] change the scale programmatically through the buttons

reference:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/16230771/233325112-eb1f60dd-a9f9-4f4b-af84-935768568793.png">

**Comment by newcat** [comment]
1. Yes, you can provide a custom connection component which gives you full control over how a connection is rendered ([docs](https://v2.baklava.tech/visual-editor/customization.html#custom-components))
2. Similar to connections, you can also provide a custom component for rendering nodes ([docs](https://v2.baklava.tech/visual-editor/customization.html#custom-components))
3. Not sure if I fully understand that part, but you can register a listener for the `beforeAddConnection` event, check if creating that connection would violate your constraints, and prevent the connection from being created in that case ([docs](https://v2.baklava.tech/event-system.html#events))
4. Yes, this is quite easy, you just need to modify the `scale` property of the currently displayed graph: `viewModel.displayedGraph.scaling += 0.1`

**Comment by mioe** [comment]
thank you very much ☺️👌🏻

**Comment by mioe** [comment]
hi @newcat, how add a many outputs to one input?
![image](https://user-images.githubusercontent.com/16230771/234842550-9589c0c5-6f24-4360-94a5-07b8c42df316.png)

**Comment by mioe** [comment]
and last) @newcat can i stretch the output port to the whole node body?
