### ISSUE TITLE
Change sidebar width

### ISSUE THREAD

**Issue by alexisrolland** [newcat/baklavajs#283]
Hello, is there an easy way to change the default width of the sidebar? I've seen the documentation here: https://newcat.github.io/baklavajs/#/styling?id=hardcore-customization but I don't really understand how to overwrite the component. I'm wondering if there could be an easier way to change the default width without overwriting entirely the component? Thanks!

**Comment by newcat** [comment]
Implemented in [v2.0.2-beta.4](https://github.com/newcat/baklavajs/releases/tag/v2.0.2-beta.4). You can use the new `sidebar` property in the settings to get/set the width and also prevent the user from resizing: https://v2.baklava.tech/api/interfaces/_baklavajs_renderer_vue.IViewSettings.html#sidebar
