### ISSUE TITLE
Expose a way to get/set the position value of the nodes

### ISSUE THREAD

**Issue by notgull** [newcat/baklavajs#284]
Hello! Thank you for the excellent library.

For the Vue plugin, it would be nice if there was an official way to get/set the positioning of the nodes. Right now we are using [this hack](https://github.com/TeamPictonode/pictonode/pull/142) which is probably not the intended way of using this library.

There might be an "official" way to do it, but I couldn't find it from a quick skim of the docs.

**Comment by newcat** [comment]
Implemented in [v2.0.2-beta.4](https://github.com/newcat/baklavajs/releases/tag/v2.0.2-beta.4)
