### ISSUE TITLE
How render all nodes and connections after fetching data?

### ISSUE THREAD

**Issue by mioe** [newcat/baklavajs#286]
Hi, are there any examples of how you convert big json to baklava entities?

in my head it looks like this:
```js
const data = await fetch()
data.nodes.forEach((n) => baklava.displayedGraph.addNode(new n, n.x, n.y))
data.connections.forEach((c) => baklava.displayedGraph.addConnection(...))
```
maybe there are better ways to do it :)

thank you in advance)

**Comment by newcat** [comment]
Do you want to replace the current state with the data from the JSON? In that case you can use the [save](https://v2.baklava.tech/api/classes/_baklavajs_core.Editor.html#save-1) and [load](https://v2.baklava.tech/api/classes/_baklavajs_core.Editor.html#load-1) functions. If you just want to add stuff based on the data, then your approach looks fine.
