### ISSUE TITLE
Node Palette Component - baklavajs v2

### ISSUE THREAD

**Issue by mleonowicz** [newcat/baklavajs#287]
Hi,

Is there a way of using existing an Node Palette Component and customising it?

I know that I can provide a custom implementation using the slot functionality (as described here: https://v2.baklava.tech/visual-editor/customization.html#custom-components), but I want to be able to base my implementation on the existing baklavajs Node Palette implementation.

Basically, adding `NodePalette.vue` to the `index.ts` in `renderer-vue` which defines exported objects would solve my issue. 

Thanks in advance :)

**Comment by newcat** [comment]
That is indeed missing in the `index.ts`, thanks for letting me know :+1:

**Comment by newcat** [comment]
Fixed in [v2.0.2-beta.4](https://github.com/newcat/baklavajs/releases/tag/v2.0.2-beta.4)
