### ISSUE TITLE
Suggestion: comment boxes and groups

### ISSUE THREAD

**Issue by Stumblinbear** [newcat/baklavajs#29]
Add boxes for comments, and a system for grouping multiple nodes together.

**Comment by newcat** [comment]
Grouping is planned in the roadmap: https://github.com/newcat/baklavajs/projects/1

For comments I would suggest creating either a node with no inputs & outputs and a textbox as node option, where you can enter your comment.

I will close this issue for now; if there is any reason why the above mentioned approach won't work for you, just reopen it and we can discuss further.

**Comment by Stumblinbear** [comment]
Well, sub-graphs isn't really what I had in mind. I meant more as an organizational measure. Allow creating a distinctly colored area where nodes can be placed and moved around as if they were one, however, not in a completely different graph. Does that make sense?
