### ISSUE TITLE
Feature Request : multi-selection with a drag

### ISSUE THREAD

**Issue by lpequignot** [newcat/baklavajs#298]
Hello,

I know it's possible to do a multi-selection by clicking Control while clicking on each node you want to select.

Would it be possible to add another multi-selection mode by clicking and dragging in the workspace to draw a marquee around the nodes you want to select ?

Regards,

Louise

**Comment by newcat** [comment]
That would certainly be a useful feature. I'll add it to the backlog

**Comment by newcat** [comment]
Implemented in [v2.4.0](https://github.com/newcat/baklavajs/releases/tag/v2.4.0)

**Comment by lpequignot** [comment]
Thank you ! I just tested it this morning with latest 2.4.1 version.
