### ISSUE TITLE
[help] Is it possible to connection back to the step?

### ISSUE THREAD

**Issue by mioe** [newcat/baklavajs#301]
![photo_2023-06-30 18 10 38](https://github.com/newcat/baklavajs/assets/16230771/84429b49-d02d-43ea-8feb-c638e4703906)
Hi, is it possible to do this?
Step 03 -> to Step 02

**Comment by newcat** [comment]
This should already be possible when you don't use the `DependencyEngine`. If you are using the `DependencyEngine`, this would result in an infinite loop during node calculation, that's why the engine is preventing cycles if it is enabled.

**Comment by mioe** [comment]
> This should already be possible when you don't use the `DependencyEngine`. If you are using the `DependencyEngine`, this would result in an infinite loop during node calculation, that's why the engine is preventing cycles if it is enabled.

thx
