### ISSUE TITLE
Is there any way to disable ContextMenu and multiple nodes selection?

### ISSUE THREAD

**Issue by YarikMamykin** [newcat/baklavajs#303]
Hello everyone,
Currently I am struggling to understand how can I disable ContextMenu and multiple nodes selection. Those features are not required for my purposes and will, most likely, lead users to bad experience. 

Maybe you could provide some examples on how to do that?

Thanks!
Best regards,
Yaroslav

**Comment by newcat** [comment]
Are you using v2? In that case, you can disable multiple nodes selection using this code snippet:
```js
import { watch } from "vue";
import { useBaklava } from "@baklavajs/renderer-vue";

const baklavaView = useBaklava();
watch(
    () => baklavaView.displayedGraph.selectedNodes.length,
    () => {
        if (baklavaView.displayedGraph.selectedNodes.length > 1) {
            baklavaView.displayedGraph.selectedNodes = baklavaView.displayedGraph.selectedNodes.slice(-1);
        }
    },
);
```

If you are using TypeScript you might need to add the following override to prevent type errors:
```ts
import { AbstractNode } from "@baklavajs/core/dist/node";
declare module "@baklavajs/core/dist/graph" {
    interface Graph {
        selectedNodes: AbstractNode[];
    }
}
```

To hide the context menu on the nodes, you can use CSS:
```css
.baklava-node .__menu {
  display: none;
}
```

**Comment by YarikMamykin** [comment]
@newcat thank you for quick response. I am using Vue3, but I think I've got your idea. If `selectedNodes` is reactive property of `Editor` then changing it the way you proposed might work. Thanks!
