### ISSUE TITLE
Long context menus go off screen

### ISSUE THREAD

**Issue by Stumblinbear** [newcat/baklavajs#31]
In the event that the context menu has many many items, it can regularly go off screen. Perhaps bump the menu up when it's displayed, and if it's excessively long, make a scroll bar?

**Comment by newcat** [comment]
Menu flipping is implemented with #35. I am not planning of implementing scroll bars soon, unless huge context menus are getting a real concern

**Comment by Stumblinbear** [comment]
I'm not 100% sure what you mean by menu flipping, but I'll take your word for it :P

**Comment by Stumblinbear** [comment]
Sub-menus don't flip correctly. They also don't flip along the X axis, though I'd imagine that'd be quite annoying to add

**Comment by newcat** [comment]
Umm yes, forgot that one. In my imagination it is not too hard to add, I will try it.

**Comment by newcat** [comment]
Implemented with 5bd5b7cfa8d67f789ca5a8f5f9adbed98c0bf315

**Comment by Stumblinbear** [comment]
Note: the Add Node submenu flips correctly, however if you move it just barely on screen, then submenus within the Add Node submenu will go off screen.

![image](https://user-images.githubusercontent.com/11092351/62086359-ab5b5600-b223-11e9-8059-bcad5a761bfc.png)

**Comment by newcat** [comment]
Thought I'd change a simple thing before pushing.... Well that broke the entire flipping :D fixed it now
