### ISSUE TITLE
[v2] docs is not lastest

### ISSUE THREAD

**Issue by YunYouJun** [newcat/baklavajs#316]
I see docs code is right.

![image](https://github.com/newcat/baklavajs/assets/25154432/f17a1553-3f0a-496d-ae1a-efb27d148f8a)

But docs is old.

![image](https://github.com/newcat/baklavajs/assets/25154432/877fe75e-4df6-4638-92ae-a12f1efdcda6)

https://v2.baklava.tech/nodes/interfaces.html#display-component

**Comment by newcat** [comment]
Yes, the online docs will be updated with the next version (docs deployment is part of the release pipeline)
