### ISSUE TITLE
how to inverse input output vertical order ?

### ISSUE THREAD

**Issue by eviltik** [newcat/baklavajs#319]
Is it possible to switch the order ? i.e inputs at he top, output at the bottom 

```
const CommandeNode = BaklavaJS.Core.defineNode( {
      type: "Execute commande",
      inputs: {
        command: () => new BaklavaJS.RendererVue.TextInputInterface( "command", "ping $1" ),
        operation: () => new BaklavaJS.RendererVue.SelectInterface( "Operation", "Addition", [ "Addition", "Subtraction", "Sine" ] ),

      },
      outputs: {
        stdoutc: () => new BaklavaJS.RendererVue.TextInputInterface( "stdout content" ),
        stderrc: () => new BaklavaJS.RendererVue.TextInputInterface( "stderr content" ),
        stdoutl: () => new BaklavaJS.RendererVue.TextInputInterface( "stdout lines" ),
        stderrl: () => new BaklavaJS.RendererVue.TextInputInterface( "stderr lines" ),
      },
    } );
```

Currently, inputs are at the bottom, outputs at the top.
![image](https://github.com/newcat/baklavajs/assets/4477890/657cca18-3aa0-47f1-beff-63fa86c40161)

Thank you !

**Comment by eviltik** [comment]
Actual

![image](https://github.com/newcat/baklavajs/assets/4477890/7f3a32d0-5918-4ff4-b56b-e914980b8a4b)

Expected

![image](https://github.com/newcat/baklavajs/assets/4477890/d8832fe0-5175-45cc-bb54-a14b48cb24b9)

( inverse divs order)

**Comment by RGamberini** [comment]
@eviltik Add the following style rule to your CSS:
```css
.baklava-node > .__content {
    display: flex;
    flex-direction: column-reverse;
}
```
Before / After
![image](https://github.com/newcat/baklavajs/assets/1889821/a09f1231-8798-425d-8969-6a84776c31ce)

**Comment by eviltik** [comment]
Thank you !!
