### ISSUE TITLE
how to create a custom input interface type ( v2 browser build ) ?

### ISSUE THREAD

**Issue by eviltik** [newcat/baklavajs#322]
Hello,

How to create a custom input interface type using browser build ?

I started using

```
class MyNodeInterface extends BaklavaJS.Core.Node {
      constructor() {
        super();
        this.initializeIo();
      }
}

```

but it failed with "can not be invoked without New" (line = super())

Any hints ?

Thank you

**Comment by yojeek** [comment]
Just borrow code of some of built-in interfaces as a boilerplate : 

https://github.com/newcat/baklavajs/tree/dev-v2.0/packages/renderer-vue/src/nodeinterfaces/textinput

**Comment by newcat** [comment]
You need to extend from `BaklavaJS.Core.NodeInterface`:
```js
class MyNodeInterface extends BaklavaJS.Core.NodeInterface {
  constructor() {
    super("MyNodeInterface", 0);
  }
}
```
