### ISSUE TITLE
Suggestion: style bezier connection

### ISSUE THREAD

**Issue by Stumblinbear** [newcat/baklavajs#33]
In the event a connection port is styled a different color, it would be very useful to be able to make a distinction between connection lines by styling the line the same color as the ports they connect between.

**Comment by newcat** [comment]
I tried that, but especially when connecting ports of different colors it starts to look pretty ugly. But through render hooks this is possible, so I will leave that for the developers that want to do it.

**Comment by Stumblinbear** [comment]
I had already attempted to do it through hooks, however the event doesnt contain enough information to determine the node port type, unless I missed something.

**Comment by newcat** [comment]
You are right. I will add the necessary information to the hook
