### ISSUE TITLE
Feature Request :  Convert a graph to a node

### ISSUE THREAD

**Issue by birth4fire** [newcat/baklavajs#346]
I have a requirement to convert a graph into a node, save it to the database, and allow others to download this node to add it to the NodePalette for general usage.  How can I implement it

**Comment by newcat** [comment]
You can create a new `GraphTemplate` using the [`fromGraph`](https://v2.baklava.tech/api/classes/_baklavajs_core.GraphTemplate.html#fromGraph) function:
```js
import { useBaklava, GraphTemplate } from "baklavajs";
const baklava = useBaklava();
const template = GraphTemplate.fromGraph(baklava.editor.graph, baklava.editor);
JSON.stringify(template.save()) // => string that you can save in the database
```

To load a graph template into other editors:
```js
import { useBaklava, GraphTemplate } from "baklavajs";
const baklava = useBaklava();
const state = JSON.parse("<string from the database>");
const template = new GraphTemplate(state, baklava.editor);
baklava.editor.addGraphTemplate(template);
```
