### ISSUE TITLE
Feature Request : convert a graph into a function

### ISSUE THREAD

**Issue by birth4fire** [newcat/baklavajs#350]
I have a requirement to design a computational process on the browser side and periodically invoke it on the server side.

**Comment by newcat** [comment]
See the [engine documentation](https://v2.baklava.tech/execution/setup.html). You can export the graph browser-side using the [`save()`](https://v2.baklava.tech/editor/saving-loading.html) function, load it server-side and execute it using an engine. You can even send the calculation results back to the client and update the nodes using the [`applyResult`](https://v2.baklava.tech/execution/setup.html#applying-the-result-to-the-graph) helper function.
