### ISSUE TITLE
Copy-Paste from a text control also duplicates the node

### ISSUE THREAD

**Issue by hthomas92** [newcat/baklavajs#352]
When pasting text into a node's TextInputInterface control,  a copy of a node will be also pasted if present on the clipboard.

Steps to reproduce:
1. Select a node and press ctrl-c. (This is needed so we have a node on the clipboard).
2. Select some text in another application and press ctrl-c.
3. Click into the text input control of any node and press ctrl-v. The text will be inserted into the control, but the originally selected node will be also pasted into the graph.

An alternative way to reproduce is to just select a node with a text input, select the text inside the node, press ctrl-c, then press ctrl-v immediately while still inside the text control, and the node will be duplicated.

The issue is also present when pasting text into a NumberInterface.

**Comment by newcat** [comment]
Fixed in [v2.3.0](https://github.com/newcat/baklavajs/releases/tag/v2.3.0)
