### ISSUE TITLE
feature request: Add support for calling preventdefault from Hotkeys

### ISSUE THREAD

**Issue by skadefro** [newcat/baklavajs#362]
Could you add a way to call "preventdefault" when an otkey has been triggered ?

For instance, i have 
```
baklava.commandHandler.registerCommand("SelectAll", {
    canExecute: () => { return true; },
    execute: () => {
      baklava.displayedGraph.selectedNodes = baklava.displayedGraph.nodes;
      return true;
    },
});
baklava.commandHandler.registerHotkey(["Control", "a"], "SelectAll");
```
This works perfectly, but it also selects everything on the page, witch is super annoying when the designer is hosted on a page with other elements.
Simply passing the event to execute or making it an option to get it called when we call registerCommand would be nice.

**Comment by newcat** [comment]
Implemented in [v2.4.0](https://github.com/newcat/baklavajs/releases/tag/v2.4.0)
