### ISSUE TITLE
Feature request: Is it possible to add a right-click selection feature?

### ISSUE THREAD

**Issue by chuteany** [newcat/baklavajs#368]
right-click selection：
![1706496038390](https://github.com/newcat/baklavajs/assets/152139999/5d8dc1da-3b3b-42a1-9c80-ff8fc807cbad)

Performing various operations on multiple nodes selected simultaneously：
![1706496092550](https://github.com/newcat/baklavajs/assets/152139999/2116c018-2244-442f-820c-228444656cb3)

**Comment by starker-xp** [comment]
For the moment, it's possible to select several elements at once with shift or ctrl, then shift or ctrl + right click to copy/paste.

![image](https://github.com/newcat/baklavajs/assets/514436/ae01fc74-fc77-4a08-99dc-18b58bdb9390)

**Comment by birth4fire** [comment]
I know this, but I feel that this method of multi-selection is not efficient enough. It would be great if both methods could be used together.

**Comment by starker-xp** [comment]
In the end, I implemented the feature because it's so practical haha. I'll go over it again tomorrow before sending it to PR.

**Comment by birth4fire** [comment]
That's great!

**Comment by newcat** [comment]
Implemented in [v2.4.0](https://github.com/newcat/baklavajs/releases/tag/v2.4.0)
