### ISSUE TITLE
Right-clicking to display the node palette shows it at the wrong position. I think the floating node palette shouldn't appear when right-clicking in the node palette area.

### ISSUE THREAD

**Issue by chuteany** [newcat/baklavajs#370]
![image](https://github.com/newcat/baklavajs/assets/152139999/0a445cb7-57c0-409e-94aa-fde7862360a8)

**Comment by starker-xp** [comment]
May it's fix in this PR https://github.com/newcat/baklavajs/pull/358. it's not release ATM

**Comment by newcat** [comment]
Fixed in [v2.4.0](https://github.com/newcat/baklavajs/releases/tag/v2.4.0)
