### ISSUE TITLE
Input with `allowMultipleConnections: true` not handled correctly when made into a Subgraph

### ISSUE THREAD

**Issue by yojeek** [newcat/baklavajs#377]
Subgraph need to retain all connections for its inputs.

<img width="600" alt="Screenshot 2024-02-06 at 15 15 03" src="https://github.com/newcat/baklavajs/assets/464535/d647da23-62d3-4825-a2c4-eca8462ef20a">

Now only one connection is retained after Subgraph created.

<img width="600" alt="Screenshot 2024-02-06 at 15 13 02" src="https://github.com/newcat/baklavajs/assets/464535/f07d47aa-40ff-4d87-83cf-6a52b77a88cb">

**Comment by newcat** [comment]
Fixed in [v2.4.1](https://github.com/newcat/baklavajs/releases/tag/v2.4.1)
