### ISSUE TITLE
Connection Line Issue

### ISSUE THREAD

**Issue by chuteany** [newcat/baklavajs#388]
When I save, there is a connection line, but it disappears when I reload. When I manually reconnect, it looks like the video below.

https://github.com/newcat/baklavajs/assets/152139999/deae5689-eebb-4d2e-824f-533bca4a0087

**Comment by newcat** [comment]
Unfortunately, I am unable to reproduce. Can you give detailed instructions on how to reproduce this issue, please?

**Comment by chuteany** [comment]
Sorry, I haven't been able to reproduce it either. Let me observe it again.

**Comment by newcat** [comment]
I'll close this issue for now, if you are able to reproduce it, then feel free to re-open
