### ISSUE TITLE
Allow certain nodes to opt-in to having multiple incoming connections

### ISSUE THREAD

**Issue by Stumblinbear** [newcat/baklavajs#41]
Since my system is more about flow of execution rather than math, the ability for certain types of ports to accept multiple connections would be wonderful.

**Comment by newcat** [comment]
I actually have been wanting to implement this for a long time, as the requirement of one connection per input interface is mostly for the engine plugin. The restriction should not be imposed by the core. Will change that as soon as I have enough time to properly test everything.

**Comment by newcat** [comment]
Implemented with b668ade94046e4ff891ddf6dcbf915a43b9d6ffd. However, since connections can't be selected currently, removing a specific connection from an input interface with multiple incoming connection is not a good UX at the moment. Until selections are selectable we have to live with that.
