### ISSUE TITLE
Prevent "contextMenu" from appearing on right-click over nodes [v2]

### ISSUE THREAD

**Issue by erwanito12** [newcat/baklavajs#421]
Could you prevent the "contextMenu" from appearing when right-clicking on a node? Some of my nodes use right-clicks with custom interfaces.
![image](https://github.com/newcat/baklavajs/assets/48127155/b4aa9034-b8b0-4c3e-8728-8e3d69c32d97)

**Comment by newcat** [comment]
Fixed in [v2.6.0](https://github.com/newcat/baklavajs/releases/tag/v2.6.0)
