### ISSUE TITLE
Add ranged slider that allows users to select two numbers in the max and the min

### ISSUE THREAD

**Issue by carbotaniuman** [newcat/baklavajs#43]
I tried to write this myself but ran into stumbling blocks with the SCSS and private interfaces - this would help to let people choose a range of values they want something filtered on.

If the min and the max is 0 and 1 - then the user can choose a range such as [0.5, 0.9] or [0, 1].

**Comment by newcat** [comment]
Since this is a very specific use-case, I'd suggest using something like https://nightcatsama.github.io/vue-slider-component/#/ for this. You can add this as a custom option, as described here: https://newcat.github.io/baklavajs/#/node-options

Let me know if you need help implementing that.

**Comment by carbotaniuman** [comment]
Most of the options like BaseNumericOptions, and INodeOption are not exposed so I cannot import them. That's my main issue right now.

**Comment by newcat** [comment]
These interfaces are exported, but they are in the types directory:
```ts
import { IPlugin } from "@baklavajs/core/dist/types";
```

But you should not need them for creating a node option. I have created a gist that shows, how an range slider option can be implemented: https://gist.github.com/newcat/000621e5cfab9cb04f7f5c815698bba2

**Comment by carbotaniuman** [comment]
Thanks.
