### ISSUE TITLE
BaklavaJS menus break when Chrome DevTools is opened

### ISSUE THREAD

**Issue by carbotaniuman** [newcat/baklavajs#44]
I downloaded newcat/ledmusic3 to make sure it isn't a problem on my end. If you have the BaklavaJS canvas and you open devtools, the menus for right clicking and creating new nodes are thrown off.

**Comment by newcat** [comment]
Can you provide detailed steps to reproduce this? I can't reproduce this unfortunately, neither with the playground of BaklavaJS nor with ledmusic3. What Chrome version are you using?

**Comment by carbotaniuman** [comment]
Still an issue with Chrome Version 77.0.3865.120 (Official Build) (64-bit).

Commit used was https://github.com/newcat/LedMusic3/tree/d72738ab5fe27354d7d6852ebd778f32ccbc094b.

**Comment by newcat** [comment]
I'm afraid I still can't reproduce it, neither with the Chrome version you specified, nor with the current one (78.0.3904.70). Can you try deleting your local clone of the repository, clone it and try again? I now use more explicit versioning for the BaklavaJS versions in the project. Maybe that could help as it will completely reinstall all dependencies.

**Comment by carbotaniuman** [comment]
Would putting this inside a Vue Router affect anything?

**Comment by newcat** [comment]
It shouldn't. I have a project (https://newcat.github.io/ml-training-data-generator/#/), where BaklavaJS is used with Vue Router, but for me everything works as expected. This project, however, is using the stable release, not the `@next` version. Not sure if that makes any difference. Are you able to make a video of the problem? That may give me a hint on where the issue might be located.

**Comment by carbotaniuman** [comment]
Nevermind, it somehow works now. Thanks.
