### ISSUE TITLE
Access node state in node option??

### ISSUE THREAD

**Issue by RingoKam** [newcat/baklavajs#49]
Is there a way to access Node state within option?

Great library! But documentation is kinda sparse. I would love to contribute to the doc after I gain a better understanding of the library 🙇‍♂️

**Comment by newcat** [comment]
Yes there is. Every option component receives some props, one of them being the node instance. Example:

```js
module.exports = {
    props: ["node"],
    methods: {
        onClick() {
            this.node.state.counter++;
        }
    }
}
```

Admittedly, the documentation is not very good at the moment. I actually reworked the documentation about node options a few days ago, but apparently it is still not clear. Maybe I should add some code examples like the one above. Would that help?

**Comment by RingoKam** [comment]
Awesome! Thanks for the quick reply.

As far as the doc goes, having the project written in typescript definitely help me navigate the library and understand what each part does. More code example would definitely helped. 

How about adding code sandbox to the doc?

Setting up based on https://newcat.github.io/baklavajs/#/plugins/view
https://codesandbox.io/s/baklavajs-setup-zvevk

Creating a customNode:
https://codesandbox.io/s/baklavajs-customnode-i0lzl

Some unrelated questions:
If I want to have more granular control over the node component, let say I want to change the template of the node itself, is extending the Node.vue component is the way to go?

**Comment by newcat** [comment]
I really like the code sandbox idea and will definetely implement that.

Yes you can "extend" the node component. Unfortunately, extending in Vue is not really possible, so you have to copy the source code and modify the copy. Have a look here (hope it helps 😉): https://newcat.github.io/baklavajs/#/styling?id=hardcore-customization

**Comment by RingoKam** [comment]
yup thats what i needed! thank you 🙇‍♂️

closing this issue.
