### ISSUE TITLE
Electron sample

### ISSUE THREAD

**Issue by Dmunch04** [newcat/baklavajs#50]
Hi

Can anybody provide me with an example of how it could/should work together with Electron? I really have no idea how it's supposed to work together

Thanks

**Comment by newcat** [comment]
Do you already have an Electron project running with Vue?

**Comment by Dmunch04** [comment]
Nope. Shortly after creating the issue, I found out you needed to create a Vue project with the CLI (I'm new to Vue). Altough I'm having problems with my system not being able to detect `vue` as a command. I'll try and add the global node modules folder to my PATH

**Comment by newcat** [comment]
I'll close this for now, as it works out-of-the box for me when using https://github.com/nklayman/vue-cli-plugin-electron-builder. Reopen, if you need more documentation/samples.
