### ISSUE TITLE
How to set the value of text input?

### ISSUE THREAD

**Issue by xpresas** [newcat/baklavajs#51]
```import { Node, NodeInterface } from "@baklavajs/core";
export default class PrintNode extends Node {
    constructor() {
        super();
        this.type = "PrintNode";
        this.name = this.type;
        this.addInputInterface("Value");
        this.addOption("input_field","InputOption");
        this.addOption("Text_field", "TextOption", "empty");
    }
    load(state) {
        super.load(state);
    }
    calculate() {
        let asd = "Nothing";
        **this.getOptionValue("Text_field") = asd;**
        console.log(asd);
    }
}
```

So I am trying to pass a string from one Node to this Print node. And I just noticed that I can really jus pass string to text_field option value to change it. Could you help me? 

I kinda went around this problem and used InputOption and then used setOptionValue.

Also could you please provide any examples on how to save all nodes and then load them? There are not much information in documentation (examples)

**Comment by newcat** [comment]
If I understood you correctly, you want to display the string, that is passed into your `Value` input interface using the `Text_field` option (correct me if I am wrong):
```ts
export default class PrintNode extends Node {
    constructor() {
        super();
        this.type = "PrintNode";
        this.name = this.type;
        this.addInputInterface("Value");
        this.addOption("input_field","InputOption");
        this.addOption("Text_field", "TextOption", "empty");
    }
    calculate() {
        this.setOptionValue("Text_field", this.getInterface("Value").value);
    }
}
```

About saving and loading:

**Saving**
```ts
const data = editor.save();
const dataString = JSON.stringify(data);
// save this string somewhere
console.log(dataString);
```

**Loading**
```ts
// load the string from somewhere and store it in the dataString variable
const data = JSON.parse(dataString);
editor.load(data);
```

Unless you want to implement some custom logic, you don't need to override the `save` and `load` methods in your nodes. By default, it will save and load everything automatically.

Hope this helps.

**Comment by xpresas** [comment]
@newcat Thank you for examples. To be honest I kinda figured it out by playing lastnight. Still thank you these examples will be a huge help continuing with BaklavaJs. Altho you should probably add these examples in your documentation. Wish you good luck and thank you!

**Comment by newcat** [comment]
Yes, updating the documentation is definitely on top of my priority list. Thanks for the kind words!
