### ISSUE TITLE
Changing cursor position via mouse not possible in textarea (Firefox)

### ISSUE THREAD

**Issue by newcat** [newcat/baklavajs#52]
The exception for `-moz-user-select` also needs to include `textarea` (and maybe other elements? Maybe also add a special class to this exception that users can apply to their controls/options?) https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-renderer-vue/src/styles/node-editor/node-editor.scss#L17

**Comment by andreibosco** [comment]
Just had this issue and ended up creating a class called `input-user-select` on my custom css file and adding it to textarea inputs.  Also, this was also creating some other issues on firefox (copy/past/cut wasn't working, sometimes pressing delete with some text selected ended up deleting the node).

I can create a PR for it (adding the class to the sass file), or were you thinking about implementing something more elaborate?
```css
.node-editor .input-user-select {
  user-select: auto;
  -moz-user-select: auto;
}
```

**Comment by newcat** [comment]
No this was pretty much what I was thinking of. A PR would be great, thanks :)
