### ISSUE TITLE
Need some help/clarification using this library inside a Vue app

### ISSUE THREAD

**Issue by halexandra** [newcat/baklavajs#53]
Hi!

I would like to use this library inside a Vue application.

As far as I understand, I need to create custom node types (I used the nodeBuilder for this) and registering them inside the created() Vue lifecycle hook. After that I have an editor instance and I can select my custom node types from the context menu. The engine needs for calculation and it could be automatic. It is ok and clear I think.

But after that, how could I access these calculated results/values outside typscript nodes to access them for later using in my Vue app?
Should I use for this: the engine? subscribing events? or how?

How could I pass some params from the Vue app to my custom nodes? (I want to use my own dynamic values as the rootNode value).

Thanks

**Comment by newcat** [comment]
Hi, do you use the automatic execution feature of the engine plugin or do you call the `calculate` function manually?

**Comment by halexandra** [comment]
I'm using the automatic execution (pass true to the constructor function)

**Comment by newcat** [comment]
Ok, unfortunately I didn't implement events and hooks for the engine yet. This is what you need to do this. I will try to add this functionality (and also document it ;) ) in the next few days (hopefully).

**Comment by halexandra** [comment]
Wow, it would be great. Thank you for your help!

**Comment by newcat** [comment]
Implemented in version `1.5.2`.

Documentation: https://newcat.github.io/baklavajs/#/plugins/engine?id=providing-data-for-calculation-and-getting-the-results

In case you got any issues or the documentation is not clear, just reopen the issue. I hope this is what you need :)
