### ISSUE TITLE
Vue node v-for :key issue when re-loading data?

### ISSUE THREAD

**Issue by scottbez1** [newcat/baklavajs#54]
I've been building some nodes with dynamic interfaces (similar to AdvancedNode in the playground), and when testing the `editor.load()` behavior to make sure I restore nodes correctly, I noticed some odd behavior with `load()` that seems like a bug. Apologies if I'm misunderstanding something, as I'm new to both Vue and baklavajs.

## Steps to reproduce:
Video: https://www.dropbox.com/s/1nho08p4trd6vdg/baklavajsBugReport.mov?dl=0
- In the playground, create an AdvancedNode
- Click Add Input 4 times; see that 4 inputs are created
- "save" the state - this should generate something like `{"nodes":[{"type":"AdvancedNode","id":"node_15859890385070","name":"AdvancedNode","options":[["Add Input",null],["Remove Input",null]],"state":{},"interfaces":[["Input 1",{"id":"ni_15859890416291"}],["Input 2",{"id":"ni_15859890422752"}],["Input 3",{"id":"ni_15859890428753"}],["Input 4",{"id":"ni_15859890466834"}]],"position":{"x":414,"y":128},"width":200,"twoColumn":false}],"connections":[],"panning":{"x":0,"y":0},"scaling":1}`
- click Remove Input and see that Input 4 is removed as expected
- _without reloading the page_, "load" the state saved earlier. Input 4 should be restored from the saved state
- click Remove Input. **Expected:** Input 4 is removed as before. **Actual:** Nothing happens visually or in the DOM; however, if you click/drag the node, the component will then update to show the correct inputs

## Investigation:
I suspect the issue stems from the fact that nodes (and their corresponding Vue components) are getting torn down and recreated during the load(), and when they're recreated their `id` is also being restored (as expected, so that their state can be restored as well).

It looks like normally changes to a Node's interfaces trigger updates of the Vue component via the Node's events, which are subscribed to in `mounted()` (https://github.com/newcat/baklavajs/blob/574752c3e8c9bc71e05730b3fa8c810f748dbe38/packages/baklavajs-plugin-renderer-vue/src/components/node/Node.vue#L156)

However, when I inspect the Node that was created by the `load()`, it doesn't have any listeners registered on its addInterface/removeInterface events, unlike the original Node. That seems to match the observed behavior -- changes to the interfaces don't trigger the DOM to update, since there's no listener registered to trigger a forceUpdate, but taking another action like clicking/moving the node modifies some other reactive state and causes Vue to update with the latest data.

I'm not familiar with Vue's caching/reuse strategy, but my hunch is that this behavior could be due to Vue caching the old `Node.vue` component instance, and then reusing that instance for the new Node. The new Node would have the same `.id` value that's used as the `v-for` `:key` attribute (https://github.com/newcat/baklavajs/blob/5e9df6b1470105f2faa3d786acf5d9b0d9c875f4/packages/baklavajs-plugin-renderer-vue/src/components/Editor.vue#L30). Again, I'm new to Vue, but I'm guessing that in a reuse case like this, the component does not get re-mounted, so the Vue component is actually still registered to the old Node's events rather than the new Node's events?

If my assumptions are correct, then it seems like one potential fix would be to change the `:key` value so it's a truly unique id per Node instance, rather than the `.id` which gets restored when a Node is `load()`ed from saved state.

Hopefully this makes sense and is helpful! And thanks so much for building this project, I've really enjoyed working with it so far!

**Comment by newcat** [comment]
Wow, good catch! And an awesome issue description - if everybody would post issues like this, we probably wouldn't have any bugs in open source software anymore 😜 

As you correctly identified, the problem is that the `mounted` hook is not called again when the underlying node instance changes. I could use a composite key (`node.id` + some random value that identifies the actual node instance) but I want to first check if there are other solutions as well. I'll try to provide a fix in the next few days.

Thanks for your feedback!

**Comment by newcat** [comment]
Well, "next few days" turned out to be half a year. But it is finally fixed now in v1.7.4!
