### ISSUE TITLE
Mismatch between Node.addOption and NodeBuilder.addOption

### ISSUE THREAD

**Issue by scottbez1** [newcat/baklavajs#56]
Node.addOption has a default parameter defaultValue that defaults to `null`, but NodeBuilder.addOption has an _optional_ parameter defaultValue which therefore is `undefined` if not set. However, you can't set `null` as the defaultValue with a NodeBuilder (to match the Node behavior) because it checks `typeof` the value and throws because `typeof(null)` is `"object"`.

Not a major issue, but it did catch me off-guard

**Comment by newcat** [comment]
Wow, well spotted. I now changed all default values (for input interfaces as well as options) for both the node builder and the node class to `null` and also allowed `null` as a default value for the node builder. Should work in v1.5.4.
