### ISSUE TITLE
Blur event isn't called

### ISSUE THREAD

**Issue by pixldev** [newcat/baklavajs#59]
Hi, blur event on html elements isn't called when I start dragging baklavajs nodes. Any ideas how to fix this?

**Comment by newcat** [comment]
On which HTML elements? Are they inside the node editor or somewhere else on your page? And how do you subscribe to the event?

**Comment by pixldev** [comment]
@newcat These elements are buttons with vue @blur and they are not inside node editor.

**Comment by newcat** [comment]
👍 fixed in version 1.5.5. Thanks for the issue!

**Comment by rodrigogomesantos** [comment]
i still the same problem when i zoom out!
