### ISSUE TITLE
Select option doesn't work

### ISSUE THREAD

**Issue by pixldev** [newcat/baklavajs#60]
Hello, I'm using this example code from BaklavaJS docs (https://newcat.github.io/baklavajs/#/custom-nodes?id=class) and my select option looks like this https://imgur.com/TzcKsm3 and I can't select any option. I'm doing something wrong?

Vue 2.6.11
Electron 8.2.3

**Comment by newcat** [comment]
Oh wow I didn't know I used the code there. The API has changed:
```js
this.addOption("Operation", "SelectOption", "Add", undefined, { items: [ "Add", "Subtract" ] });
```
The updated documentation for the options can be found here: https://newcat.github.io/baklavajs/#/plugins/options (admittedly it is missing code examples and therefore not really clear).

**Comment by pixldev** [comment]
It's working now. Thank you!
