### ISSUE TITLE
baklavajs for data model UI

### ISSUE THREAD

**Issue by tpoxa** [newcat/baklavajs#67]
Hi, thanks for your outstanding work. I would like to try to use baklavajs for data model editor. Where use has something alike tables and can create relations in between. 
Question. Is that possible to make connection clickable? I would like to display a dialog with connection options.

Any suggestions maybe how to use baklavajs for such purposes as mine?

Thanks.

**Comment by newcat** [comment]
For the clickable connections: Yes, but it's not that easy. You basically have to create your own connection component, which wraps around the original `ConnectionWrapper` component and handles the click event to show your custom dialog. See [here](https://newcat.github.io/baklavajs/#/styling?id=hardcore-customization) for more info.

With data model editor you mean something like a ERM editor? In that case, Baklava wasn't designed with your use-case in mind, but rather for dataflow programming purposes. Therefore I am not sure, how well it'll work.

**Comment by tpoxa** [comment]
Yes my future project has both the flow style programming for processes and simple data models. I would like to use the same engine for both, but it's not so important.
My ERP editor requirements are not so different basically.

<img width="778" alt="Screenshot 2020-05-20 at 09 36 04" src="https://user-images.githubusercontent.com/431546/82413043-58d27b00-9a7d-11ea-951d-48d6f5225c89.png">
I will try to do something alike with baklavajs. 
Thanks for tips.

BTW. What happened with the old cat? :)

**Comment by newcat** [comment]
I hacked something together real quick, but I am not really proud of it and it's not really user friendly:
![Quick Example](https://user-images.githubusercontent.com/1523157/82567998-75a2a780-9b7e-11ea-9b9d-dcc09d5ef01b.png)

Code: https://gist.github.com/newcat/0e72276243f71779debc86085ef9a78d

You'd have to replace the Assignment, Group and Client node with a general `Entity` node, which allows the user to edit the properties (aka output interfaces in this case) manually. Something like the [AdvancedNode](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-playground/src/AdvancedNode.ts) in the playground or this [FunctionNode](https://github.com/newcat/ml-training-data-generator/blob/master/src/nodes/FunctionNode.ts) in one of my other projects.

PS: Old cat is dead, long live the newcat 😜

**Comment by tpoxa** [comment]
Thank you.
