### ISSUE TITLE
Thumbnail and minimap support?

### ISSUE THREAD

**Issue by ExpandOcean** [newcat/baklavajs#68]
Hi @newcat  What you have done is really awesome!  I am using it with Vuetify for a new project. Is there a way to create a thumbnail with current node editor? So that the diagram could be selected by the thumbnail. Also, is it possible to have minimap support? It's really useful for navigating when there're many nodes in the editor.
Thanks!

**Comment by newcat** [comment]
Thank you! I agree that having a minimap really helps. I'll try to implement that as soon as possible. For the thumbnail part: Do you mean like a screenshot of the node editor? Or rather a simplified version like the minimap?

**Comment by ExpandOcean** [comment]
I think a screenshot of the range of interest will be perfect. Maybe the editor has a screenshot() method which returned a base64 png.

**Comment by newcat** [comment]
So from my initial experiments, I am unable to get the screenshot/thumbnail part working unfortunately. But I'll continue to work on the minimap and making a thumbnail from the minimap contents can be done pretty easily, so I think that's the route I will be going.

**Comment by newcat** [comment]
Baklava v1.7.0 finally has a minimap. Took only 2 months to do it 🙈 You can enable it via `viewPlugin.enableMinimap = true` (it is disabled by default at the moment).

To make a screenshot of the minimap as thumbnail, use this code snippet:
```js
const cv = document.querySelector(".minimap");
cv.toBlob((blob) => {
    const downloadLink = document.createElement('a');
    const url = URL.createObjectURL(blob);
    downloadLink.setAttribute('download', 'thumbnail.png');
    downloadLink.setAttribute('href', url);
    downloadLink.click();
});
```
This will create a screenshot and open the browsers download dialog.

If you have any issues with the minimap, please report them. The only issue I had during testing was that moving the viewport through the minimap wasn't accurate when zoomed in/out.
