### ISSUE TITLE
Movement is too fast

### ISSUE THREAD

**Issue by Jet132** [newcat/baklavajs#84]
When I use the mouse to drag a block or the whole view around it moves at twice the speed.
I'm using the native version with angular.

Here is it recorded
https://streamable.com/ll0wpc

**Comment by Jet132** [comment]
OK, I found out that it has to do with windows UI scaling. With an uncalled UI (100%) it's fine but with anything else, it's not a 1:1 movement.

**Comment by newcat** [comment]
Yes, this is a known issue, see #20 

Unfortunately, this is an issue in Chrome/Chromium and I am not sure, if I can find a workaround. I'll have a look into it and maybe open an issue in the Chromium issue list.
