### ISSUE TITLE
Sidebar in native usage

### ISSUE THREAD

**Issue by Jet132** [newcat/baklavajs#85]
When using BaklavaJS in a native js environment is it still possible to use the sidebar?
Is there any way I can emulate a Vue component to register as an option?

**Comment by Jet132** [comment]
Closing because I decided to just use Vue for the whole project. Haven't found an answer yet though.

**Comment by newcat** [comment]
Yes, I think this is not really possible without Vue unfortunately 😢 

Theoretically, wrapping the HTML inside a Vue component would be possible, since Vue will be available in the global context, but handling the state would be a real pain. So I guess, doing everything in Vue is the way to go.

**Comment by Jet132** [comment]
Yeah It's also much nicer to work with the library as a whole anyway
