### ISSUE TITLE
how to create a node programatically

### ISSUE THREAD

**Issue by ViiMorales** [newcat/baklavajs#87]
I'm working on an app and i need to have two nodes (a start and an end) on application load.

is there a way to add a node programatically?, i'm kinda confused with the documentation. should i save the whole state and load it on application start?.

i found this method [addNode](https://newcat.github.io/baklavajs/api/index.html#/@baklavajs%2Fcore/classes/Editor#addNode) but i cant seem to find which parameters receives to add the node.

could you please provide an example?

**Comment by newcat** [comment]
You are correct that you need the `addNode` function. But you also need a node instance. So let's say you created a node type `MyNode` (either via the `NodeBuilder` or by extending the `Node` base class, as described [here](https://newcat.github.io/baklavajs/#/custom-nodes)). Then you can do:
```js
const n = new MyNode();
editor.addNode(n);
```

**Comment by ViiMorales** [comment]
yay!, thanks!. Baklava is super awesome 🤩, is there a way to position a node? while we are adding it or after it?

**Comment by newcat** [comment]
Thanks 😄 yes there is:

```js
const n = new MyNode();
editor.addNode(n);
n.position = { x: 200, y: 100 };
```

Make sure to set the position **after** the node has been added. There is a bug currently in the view plugin that overrides the position value when adding a node.

If you use TypeScript, you need to cast `n` to `any` at the moment:
```ts
(n as any).position = { x: 200, y: 100 };
```

**Comment by glight2000** [comment]
> You are correct that you need the `addNode` function. But you also need a node instance. So let's say you created a node type `MyNode` (either via the `NodeBuilder` or by extending the `Node` base class, as described [here](https://newcat.github.io/baklavajs/#/custom-nodes)). Then you can do:
> 
> ```js
> const n = new MyNode();
> editor.addNode(n);
> ```

I tried to use NodeBuilder [example](https://newcat.github.io/baklavajs/#/custom-nodes) but get vue errors:`[Vue warn]: Error in created hook: "TypeError: Cannot read property 'save' of undefined"`.

Here is my code:
```
    this.editor.addNode(new NodeBuilder("MyNode")./*Options and interfaces*/.build() );
```

**Comment by newcat** [comment]
Sure! With `NodeBuilder`, you would do it like this:
```js
const MyNode = new NodeBuilder("MyNode")./*Options and interfaces*/.build();
const n = new MyNode();
editor.addNode(n);
```

So the `NodeBuilder`'s `build()` function actually returns a node type, which is essentially a blueprint for a node. You can then create a instance of that node type using `new` and then add the instance to the editor.

**Comment by glight2000** [comment]
It works, :) Thanks!

**Comment by Altenrion** [comment]
How to make positioning like this:
n.position = { x: 200, y: 100 };

But with zoom scaling adoption?
How to get zoom of editor view?

**Comment by Altenrion** [comment]
I found that there are baklava.displayedGraph.scaling option. 

// const scale = baklava.displayedGraph.scaling
  const mouseX = mouseAt.x; // Example mouse X coordinate
  const mouseY = mouseAt.y; // Example mouse Y coordinate

But i was not lucky to adopt this scaling with useMouse  for now. Will be experimenting.
