### ISSUE TITLE
Disable output nodes?

### ISSUE THREAD

**Issue by andreibosco** [newcat/baklavajs#95]
Is it possible to disable output nodes if some of the node's options does not have defined values? I'm trying to achieve something like this:
![image](https://user-images.githubusercontent.com/607297/89541640-a46b0a00-d7cc-11ea-9db1-eabe5c4de94c.png)

Also, thanks for such a cool project. I'm really enjoying it.

**Comment by newcat** [comment]
Sorry for the late reply. There is no default way of doing this, and I admit, there is no easy way of custom implementing that either.

You could implement your own `NodeInterface` component based on the default implementation. [This](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-renderer-vue/src/components/node/NodeInterface.vue) page describes how to do it. The `NodeInterface` [class](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-core/src/nodeInterface.ts) allows to set additional custom properties, so whenever the value of your options (Checkbox or InputField) changes, you could set a `disabled` property in your node interface.

Here is an example of how to do it (this code would go inside the constructor of your node class):
```js
const checkboxOutput = this.addOutputInterface("Checkbox output", { disabled: true });
const checkboxOption = this.addOption("Checkbox", "CheckboxOption", false);
checkboxOption.events.setValue.addListener(this, (newValue) => {
    checkboxOutput.disabled = !newValue;
});
```

Then, inside your custom `NodeInterface` component, you could set CSS a disabled class. The CSS itself could look like this:
```css
.node-interface.--disabled .__port {
    pointer-events: none;
    background-color: darkgray;
}
```
The `pointer-events: none;` will prevent new connections from being created. Note, however, that setting the color via CSS won't work when using the interface types plugin, as it will override the color using the `style` attribute directly.

**Comment by andreibosco** [comment]
Thanks a lot for your response and providing an example, I will try to implement it this weekend.

**Comment by newcat** [comment]
I'll close this for now, feel free to reopen if you are still encountering problems.
